/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package streetSparkle;

import java.awt.CardLayout;
import java.awt.Color;

/**
 *
 * @author John Felix
 */
public class AdminUI extends javax.swing.JFrame {
    
    public Database database; // class obj
    public CardLayout cardLayout; // layout manager for changing panels on button click
    public MapsPanel mapPanel; // panel obj
    public UserProfilePanel profilePanel; // panel obj
    public HRreportsPanel HRPanel; // panel obj
    public SalesReportPanel salesPanel; // panel obj
    public SUPreportsPanel supervisorPanel; // panel obj
    public ToolsReportPanel toolsPanel; // panel obj
    public AdminAuthorizationPanel authorizationPanel; // panel obj

    /** Creates new form AdminUI */
    public AdminUI() {
        /* variable instatiation */
        database = new Database();
        cardLayout = new CardLayout();
        mapPanel = new MapsPanel();
        profilePanel = new UserProfilePanel();
        HRPanel = new HRreportsPanel();
        salesPanel = new SalesReportPanel();
        supervisorPanel = new SUPreportsPanel(); 
        toolsPanel = new ToolsReportPanel(); 
        authorizationPanel = new AdminAuthorizationPanel();
        
        initComponents(); // method invokation to set GUI components
        
        adminMainPanel.setLayout(cardLayout);
        adminMainPanel.add(HRPanel,"panel1"); // add panel obj for HR reports button click
        adminMainPanel.add(salesPanel,"panel2"); // add panel obj for sales reports button click
        adminMainPanel.add( supervisorPanel,"panel3"); // add panel obj for supervisor reports button click
        adminMainPanel.add(toolsPanel,"panel4"); // add panel obj for tools reports button click
        adminMainPanel.add(mapPanel,"panel5"); // add panel obj for maps button click
        adminMainPanel.add(authorizationPanel,"panel6"); // add panel obj for authorization button click
        adminMainPanel.add(profilePanel,"panel7"); // add panel obj for profile button click
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adminFramePanel = new javax.swing.JPanel();
        adminNavigationPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        hrReportsButton = new javax.swing.JButton();
        salesReportsButton = new javax.swing.JButton();
        supervisorReportsButton = new javax.swing.JButton();
        toolsReportsButton = new javax.swing.JButton();
        mapsButton = new javax.swing.JButton();
        authorizationButton = new javax.swing.JButton();
        profileButton = new javax.swing.JButton();
        adminMainPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Interface - Street Sparkle");
        setExtendedState(6);
        setMinimumSize(new java.awt.Dimension(1350, 700));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                windowClosingHandler(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                windowOpenedHandler(evt);
            }
        });

        adminNavigationPanel.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(new java.awt.Font("Viner Hand ITC", 0, 18)); // NOI18N
        jLabel1.setText("Admin Interface");

        hrReportsButton.setBackground(new java.awt.Color(0, 204, 204));
        hrReportsButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        hrReportsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Icons/people-poll(1).png"))); // NOI18N
        hrReportsButton.setText("HR Reports");
        hrReportsButton.setToolTipText("click to view human resource reports");
        hrReportsButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 3));
        hrReportsButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        hrReportsButton.setMargin(new java.awt.Insets(3, 14, 3, 14));
        hrReportsButton.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                navigationButtonFocusGainedHandler(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                navigationButtonFocusLostHandler(evt);
            }
        });
        hrReportsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hrReportsButtonHandler(evt);
            }
        });

        salesReportsButton.setBackground(new java.awt.Color(0, 204, 204));
        salesReportsButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        salesReportsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Icons/chart-histogram(1).png"))); // NOI18N
        salesReportsButton.setText("Sales Reports");
        salesReportsButton.setToolTipText("click to view sales & finance reports");
        salesReportsButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 3));
        salesReportsButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        salesReportsButton.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                navigationButtonFocusGainedHandler(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                navigationButtonFocusLostHandler(evt);
            }
        });
        salesReportsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salesReportsButtonHandler(evt);
            }
        });

        supervisorReportsButton.setBackground(new java.awt.Color(0, 204, 204));
        supervisorReportsButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        supervisorReportsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Icons/search-alt(1).png"))); // NOI18N
        supervisorReportsButton.setText("Supervisor Reports");
        supervisorReportsButton.setToolTipText("click to view projects supervison reports");
        supervisorReportsButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 3));
        supervisorReportsButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        supervisorReportsButton.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                navigationButtonFocusGainedHandler(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                navigationButtonFocusLostHandler(evt);
            }
        });
        supervisorReportsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supervisorReportsButtonHandler(evt);
            }
        });

        toolsReportsButton.setBackground(new java.awt.Color(0, 204, 204));
        toolsReportsButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        toolsReportsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Icons/settings-sliders.png"))); // NOI18N
        toolsReportsButton.setText("Tools Reports");
        toolsReportsButton.setToolTipText("click to view tool reports");
        toolsReportsButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 3));
        toolsReportsButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        toolsReportsButton.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                navigationButtonFocusGainedHandler(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                navigationButtonFocusLostHandler(evt);
            }
        });
        toolsReportsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toolsReportsButtonHandler(evt);
            }
        });

        mapsButton.setBackground(new java.awt.Color(0, 204, 204));
        mapsButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mapsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Icons/map-marker.png"))); // NOI18N
        mapsButton.setText("Maps");
        mapsButton.setToolTipText("click to view maps");
        mapsButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 3));
        mapsButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        mapsButton.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                navigationButtonFocusGainedHandler(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                navigationButtonFocusLostHandler(evt);
            }
        });
        mapsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mapsButtonHandler(evt);
            }
        });

        authorizationButton.setBackground(new java.awt.Color(0, 204, 204));
        authorizationButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        authorizationButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Icons/mobile.png"))); // NOI18N
        authorizationButton.setText("Authorization");
        authorizationButton.setToolTipText("click to update user's authorization");
        authorizationButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 3));
        authorizationButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        authorizationButton.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                navigationButtonFocusGainedHandler(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                navigationButtonFocusLostHandler(evt);
            }
        });
        authorizationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                authorizationButtonHandler(evt);
            }
        });

        profileButton.setBackground(new java.awt.Color(0, 204, 204));
        profileButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        profileButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Icons/user(1).png"))); // NOI18N
        profileButton.setText("Profile");
        profileButton.setToolTipText("click to view your profile");
        profileButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 3));
        profileButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        profileButton.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                navigationButtonFocusGainedHandler(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                navigationButtonFocusLostHandler(evt);
            }
        });
        profileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileButtonHandler(evt);
            }
        });

        javax.swing.GroupLayout adminNavigationPanelLayout = new javax.swing.GroupLayout(adminNavigationPanel);
        adminNavigationPanel.setLayout(adminNavigationPanelLayout);
        adminNavigationPanelLayout.setHorizontalGroup(
            adminNavigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminNavigationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(hrReportsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(salesReportsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(supervisorReportsButton, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
            .addComponent(toolsReportsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mapsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(authorizationButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(profileButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        adminNavigationPanelLayout.setVerticalGroup(
            adminNavigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminNavigationPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(hrReportsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(salesReportsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(supervisorReportsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(toolsReportsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(mapsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(authorizationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(profileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(272, Short.MAX_VALUE))
        );

        adminMainPanel.setBackground(new java.awt.Color(198, 255, 255));

        javax.swing.GroupLayout adminMainPanelLayout = new javax.swing.GroupLayout(adminMainPanel);
        adminMainPanel.setLayout(adminMainPanelLayout);
        adminMainPanelLayout.setHorizontalGroup(
            adminMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1163, Short.MAX_VALUE)
        );
        adminMainPanelLayout.setVerticalGroup(
            adminMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout adminFramePanelLayout = new javax.swing.GroupLayout(adminFramePanel);
        adminFramePanel.setLayout(adminFramePanelLayout);
        adminFramePanelLayout.setHorizontalGroup(
            adminFramePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminFramePanelLayout.createSequentialGroup()
                .addComponent(adminNavigationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(adminMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        adminFramePanelLayout.setVerticalGroup(
            adminFramePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adminNavigationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(adminMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adminFramePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adminFramePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void windowOpenedHandler(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_windowOpenedHandler
        // set window size to fullscreen when window is opened
        this.setExtendedState(AdminUI.MAXIMIZED_BOTH); 
    }//GEN-LAST:event_windowOpenedHandler

    private void navigationButtonFocusGainedHandler(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_navigationButtonFocusGainedHandler
        // change colour on focus
        if(evt.getSource() == hrReportsButton) {
           hrReportsButton.setBackground(new Color(255,153,0));
        }
        else if(evt.getSource() == salesReportsButton) {
           salesReportsButton.setBackground(new Color(255,153,0)); 
        }
        else if(evt.getSource() == supervisorReportsButton) {
           supervisorReportsButton.setBackground(new Color(255,153,0)); 
        }
        else if(evt.getSource() == toolsReportsButton) {
           toolsReportsButton.setBackground(new Color(255,153,0)); 
        }
        else if(evt.getSource() == mapsButton) {
           mapsButton.setBackground(new Color(255,153,0)); 
        }
        else if(evt.getSource() == authorizationButton) {
           authorizationButton.setBackground(new Color(255,153,0)); 
        }
        else if(evt.getSource() == profileButton) {
           profileButton.setBackground(new Color(255,153,0)); 
        }
    }//GEN-LAST:event_navigationButtonFocusGainedHandler

    private void navigationButtonFocusLostHandler(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_navigationButtonFocusLostHandler
        // change colour on focus lost
        if(evt.getSource() == hrReportsButton) {
           hrReportsButton.setBackground(new Color(0,204,204));
        }
        else if(evt.getSource() == salesReportsButton) {
           salesReportsButton.setBackground(new Color(0,204,204)); 
        }
        else if(evt.getSource() == supervisorReportsButton) {
           supervisorReportsButton.setBackground(new Color(0,204,204)); 
        }
        else if(evt.getSource() == toolsReportsButton) {
           toolsReportsButton.setBackground(new Color(0,204,204)); 
        }
        else if(evt.getSource() == mapsButton) {
           mapsButton.setBackground(new Color(0,204,204)); 
        }
        else if(evt.getSource() == authorizationButton) {
           authorizationButton.setBackground(new Color(0,204,204)); 
        }
        else if(evt.getSource() == profileButton) {
           profileButton.setBackground(new Color(0,204,204)); 
        }
    }//GEN-LAST:event_navigationButtonFocusLostHandler

    private void hrReportsButtonHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrReportsButtonHandler
        // display panel1
        cardLayout.show(adminMainPanel,"panel1");
    }//GEN-LAST:event_hrReportsButtonHandler

    private void salesReportsButtonHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salesReportsButtonHandler
        // display panel2
        cardLayout.show(adminMainPanel,"panel2");
    }//GEN-LAST:event_salesReportsButtonHandler

    private void supervisorReportsButtonHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supervisorReportsButtonHandler
        // display panel3
        cardLayout.show(adminMainPanel,"panel3");
    }//GEN-LAST:event_supervisorReportsButtonHandler

    private void toolsReportsButtonHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toolsReportsButtonHandler
        // display panel4
        cardLayout.show(adminMainPanel,"panel4");
    }//GEN-LAST:event_toolsReportsButtonHandler

    private void mapsButtonHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mapsButtonHandler
        // display panel5
        cardLayout.show(adminMainPanel,"panel5");
    }//GEN-LAST:event_mapsButtonHandler

    private void authorizationButtonHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_authorizationButtonHandler
        // display panel6
        cardLayout.show(adminMainPanel,"panel6");
    }//GEN-LAST:event_authorizationButtonHandler

    private void profileButtonHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileButtonHandler
        // display panel7
        cardLayout.show(adminMainPanel,"panel7");
    }//GEN-LAST:event_profileButtonHandler

    private void windowClosingHandler(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_windowClosingHandler
        // close database connection then exit
        database.closeDB();
        System.exit(0);
    }//GEN-LAST:event_windowClosingHandler

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel adminFramePanel;
    private javax.swing.JPanel adminMainPanel;
    private javax.swing.JPanel adminNavigationPanel;
    private javax.swing.JButton authorizationButton;
    private javax.swing.JButton hrReportsButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton mapsButton;
    private javax.swing.JButton profileButton;
    private javax.swing.JButton salesReportsButton;
    private javax.swing.JButton supervisorReportsButton;
    private javax.swing.JButton toolsReportsButton;
    // End of variables declaration//GEN-END:variables

}
