/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package streetSparkle;

import java.time.format.DateTimeParseException;
import javax.swing.JOptionPane;


/**
 *
 * @author John Felix
 */
public class HRregisterStaffPanel extends javax.swing.JPanel {
    
    public Database database; // class obj
    public Staff aStaff; // class obj

    /**
     * Creates new form HRregisterStaffPanel
     */
    public HRregisterStaffPanel() { 
        /* variable instatiation */
        database = new Database();
        aStaff = new Staff();
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registerStaffPanel = new javax.swing.JPanel();
        javax.swing.JPanel personalDetailsPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fNameTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        midNameTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        surNameTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        idTF = new javax.swing.JTextField();
        birthDateTF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        usernameTF = new javax.swing.JTextField();
        staffIDTF = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        addressTF = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        emailTF = new javax.swing.JTextField();
        phoneTF = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        passwordPF = new javax.swing.JPasswordField();
        personalDetailsSaveButton = new javax.swing.JButton();
        personalDetailsClearButton = new javax.swing.JButton();
        genderCB = new javax.swing.JComboBox<>();
        countyCB = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        perksFormattedTF = new javax.swing.JFormattedTextField();
        salaryFormattedTF = new javax.swing.JFormattedTextField();
        titleCB = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1175, 700));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                componentHiddenHandler(evt);
            }
        });

        registerStaffPanel.setBackground(new java.awt.Color(249, 251, 253));
        registerStaffPanel.setPreferredSize(new java.awt.Dimension(1175, 700));

        personalDetailsPanel.setBackground(new java.awt.Color(249, 251, 253));
        personalDetailsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0), 2), "Personal Details", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N
        personalDetailsPanel.setPreferredSize(new java.awt.Dimension(1175, 700));

        jLabel1.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setLabelFor(fNameTF);
        jLabel1.setText("First Name");

        fNameTF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fNameTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                alphabeticKeyTypedHandler(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setLabelFor(midNameTF);
        jLabel2.setText("Mid Name");

        midNameTF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        midNameTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                alphabeticKeyTypedHandler(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setLabelFor(surNameTF);
        jLabel3.setText("Sur Name");

        surNameTF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        surNameTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                alphabeticKeyTypedHandler(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setLabelFor(idTF);
        jLabel4.setText("ID");

        idTF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        idTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numericKeyTypedHandler(evt);
            }
        });

        birthDateTF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        birthDateTF.setText("YYYY-MM-DD");

        jLabel5.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setLabelFor(birthDateTF);
        jLabel5.setText("Birth Date");

        jLabel6.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setLabelFor(usernameTF);
        jLabel6.setText("Username");

        usernameTF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        staffIDTF.setEditable(false);
        staffIDTF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        staffIDTF.setToolTipText("registered staff serial number");

        jLabel8.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Staff S/N");

        jLabel10.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setLabelFor(countyCB);
        jLabel10.setText("County");

        jLabel11.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setLabelFor(genderCB);
        jLabel11.setText("Gender");

        jLabel12.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setLabelFor(addressTF);
        jLabel12.setText("Address");

        addressTF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setLabelFor(emailTF);
        jLabel13.setText("Email");

        emailTF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        phoneTF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        phoneTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numericKeyTypedHandler(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setLabelFor(phoneTF);
        jLabel14.setText("Phone");
        jLabel14.setPreferredSize(new java.awt.Dimension(66, 20));

        personalDetailsSaveButton.setBackground(new java.awt.Color(255, 204, 51));
        personalDetailsSaveButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        personalDetailsSaveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Icons/folder-download.png"))); // NOI18N
        personalDetailsSaveButton.setText("Save");
        personalDetailsSaveButton.setToolTipText("click to save personal details");
        personalDetailsSaveButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        personalDetailsSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personalDetailsSaveButtonHandler(evt);
            }
        });

        personalDetailsClearButton.setBackground(new java.awt.Color(255, 204, 51));
        personalDetailsClearButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        personalDetailsClearButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Icons/delete.png"))); // NOI18N
        personalDetailsClearButton.setText("Clear");
        personalDetailsClearButton.setToolTipText("click to clear all fields");
        personalDetailsClearButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        personalDetailsClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personalDetailsClearButtonHandler(evt);
            }
        });

        genderCB.setMaximumRowCount(2);
        genderCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MALE", "FEMALE" }));
        genderCB.setToolTipText("select gender");

        countyCB.setMaximumRowCount(5);
        countyCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MOMBASA", "KWALE", "KILIFI", "TANA RIVER", "LAMU", "TAITA/TAVETA", "GARISSA", "WAJIR", "MANDERA", "MARSABIT", "ISIOLO", "MERU", "THARAKA-NITHI", "EMBU", "KITUI", "MACHAKOS", "MAKUENI", "NYANDARUA", "NYERI", "KIRINYAGA", "MURANG'A", "KIAMBU", "TURKANA", "WEST POKOT", "SAMBURU", "TRANS NZOIA", "UASIN GISHU", "ELGEYO/MARAKWET", "NANDI", "BARINGO", "LAIKIPIA", "NAKURU", "NAROK", "KAJIADO", "KERICHO", "BOMET", "KAKAMEGA", "VIHIGA", "BUNGOMA", "BUSIA", "SIAYA", "KISUMU", "HOMA BAY", "MIGORI", "KISII", "NYAMIRA", "NAIROBI CITY" }));
        countyCB.setToolTipText("select county of residence");

        jLabel15.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setLabelFor(salaryFormattedTF);
        jLabel15.setText("Salary");

        jLabel16.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setLabelFor(perksFormattedTF);
        jLabel16.setText("Perks");

        jLabel17.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setLabelFor(titleCB);
        jLabel17.setText("Title");

        perksFormattedTF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        perksFormattedTF.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        salaryFormattedTF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        salaryFormattedTF.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        titleCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SUPERVISOR", "HUMAN RESOURCE", "SALES & FINANCE", "TOOLS MANAGER", "DRIVER", "ADMIN" }));
        titleCB.setToolTipText("select staff position title");
        titleCB.setOpaque(true);

        jLabel9.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setLabelFor(passwordPF);
        jLabel9.setText("Password");

        javax.swing.GroupLayout personalDetailsPanelLayout = new javax.swing.GroupLayout(personalDetailsPanel);
        personalDetailsPanel.setLayout(personalDetailsPanelLayout);
        personalDetailsPanelLayout.setHorizontalGroup(
            personalDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personalDetailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(personalDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(personalDetailsPanelLayout.createSequentialGroup()
                        .addGroup(personalDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, personalDetailsPanelLayout.createSequentialGroup()
                                .addGroup(personalDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(personalDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(personalDetailsPanelLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(personalDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(midNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(fNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(surNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(idTF, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(birthDateTF, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(personalDetailsPanelLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(usernameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, personalDetailsPanelLayout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(passwordPF, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(personalDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, personalDetailsPanelLayout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(staffIDTF, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, personalDetailsPanelLayout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(countyCB, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, personalDetailsPanelLayout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addressTF, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, personalDetailsPanelLayout.createSequentialGroup()
                                .addGroup(personalDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(personalDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(emailTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(phoneTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, personalDetailsPanelLayout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(genderCB, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(personalDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(personalDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(salaryFormattedTF)
                            .addComponent(titleCB, 0, 200, Short.MAX_VALUE)
                            .addComponent(perksFormattedTF, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, personalDetailsPanelLayout.createSequentialGroup()
                        .addGap(0, 206, Short.MAX_VALUE)
                        .addComponent(personalDetailsClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(138, 138, 138)
                        .addComponent(personalDetailsSaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(249, 249, 249))))
        );
        personalDetailsPanelLayout.setVerticalGroup(
            personalDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personalDetailsPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(personalDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(personalDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, personalDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(personalDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phoneTF, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(titleCB))
                .addGap(18, 18, 18)
                .addGroup(personalDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(personalDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(emailTF, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(midNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(salaryFormattedTF))
                .addGap(18, 19, Short.MAX_VALUE)
                .addGroup(personalDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addressTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(perksFormattedTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(personalDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(surNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(personalDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(personalDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(idTF, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(genderCB))
                .addGap(18, 18, 18)
                .addGroup(personalDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(personalDetailsPanelLayout.createSequentialGroup()
                        .addGroup(personalDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(countyCB, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(73, 73, 73)
                        .addGroup(personalDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(passwordPF)
                            .addComponent(staffIDTF, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                        .addGap(82, 82, 82)
                        .addGroup(personalDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(personalDetailsSaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(personalDetailsClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(94, Short.MAX_VALUE))
                    .addGroup(personalDetailsPanelLayout.createSequentialGroup()
                        .addGroup(personalDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(birthDateTF, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(personalDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usernameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout registerStaffPanelLayout = new javax.swing.GroupLayout(registerStaffPanel);
        registerStaffPanel.setLayout(registerStaffPanelLayout);
        registerStaffPanelLayout.setHorizontalGroup(
            registerStaffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerStaffPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(personalDetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        registerStaffPanelLayout.setVerticalGroup(
            registerStaffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(personalDetailsPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(registerStaffPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(registerStaffPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void alphabeticKeyTypedHandler(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_alphabeticKeyTypedHandler
        // get typed character
        char testChar = evt.getKeyChar();
        // if not alphabetic reject character        
        if(!(Character.isAlphabetic(testChar)))  {
            evt.consume();
        } 
    }//GEN-LAST:event_alphabeticKeyTypedHandler

    private void numericKeyTypedHandler(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numericKeyTypedHandler
        // get typed character
        char testChar = evt.getKeyChar();
        // if not numeric/digit reject character        
        if(!(Character.isDigit(testChar)))  {
            evt.consume();
        }
    }//GEN-LAST:event_numericKeyTypedHandler

    private void personalDetailsClearButtonHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personalDetailsClearButtonHandler
        // clear all textfields
        fNameTF.setText("");
        midNameTF.setText("");
        surNameTF.setText("");
        idTF.setText("");
        birthDateTF.setText("YYYY-MM-DD");
        usernameTF.setText("");
        passwordPF.setText("");
        phoneTF.setText("");
        emailTF.setText("");
        addressTF.setText("");
        staffIDTF.setText("");
        salaryFormattedTF.setText("");
        perksFormattedTF.setText("");
        personalDetailsSaveButton.setEnabled(true);
    }//GEN-LAST:event_personalDetailsClearButtonHandler

    private void personalDetailsSaveButtonHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personalDetailsSaveButtonHandler
        // confirm text fields not empty
        if(fNameTF.getText().isBlank() || midNameTF.getText().isBlank() || surNameTF.getText().isBlank() || idTF.getText().isBlank() || birthDateTF.getText().isBlank() || 
                usernameTF.getText().isBlank() ||  passwordPF.getText().isBlank() || phoneTF.getText().isBlank() || emailTF.getText().isBlank() ||
                addressTF.getText().isBlank() || salaryFormattedTF.getText().isBlank() || perksFormattedTF.getText().isBlank()) {
            // display error message
            JOptionPane.showMessageDialog( null, "Please Fill All Fields!", "Add New Staff Error - Street Sparkle", JOptionPane.WARNING_MESSAGE );
        } else {
            try {                
                String staffGender = genderCB.getSelectedItem().toString();
                String staffCounty = countyCB.getSelectedItem().toString();
                String staffTitle = titleCB.getSelectedItem().toString();
                float salary = Float.parseFloat(salaryFormattedTF.getValue().toString());
                float perks = Float.parseFloat(perksFormattedTF.getValue().toString());
                // validate input id value
                if(Authenticator.validateID(idTF.getText()) == false) {
                    // display error message
                    JOptionPane.showMessageDialog( null, "Please input a valid ID number (8 digits)!", "Add New Staff Error - Street Sparkle", JOptionPane.WARNING_MESSAGE );
                }
                // validate date of birth input
                else if(Authenticator.validateDate(birthDateTF.getText()) == false) {
                    // display error message
                    JOptionPane.showMessageDialog( null, "Please input valid Date!\neg.2023-05-03", "Add New Staff Error - Street Sparkle", JOptionPane.WARNING_MESSAGE );
                }
                // validate mobile phone no. input
                else if(Authenticator.validateMobileNo(phoneTF.getText()) == false) {
                    // display error message
                    JOptionPane.showMessageDialog( null, "Please input a valid Mobile Phone number (10 digits)!", "Add New Staff Error - Street Sparkle", JOptionPane.WARNING_MESSAGE );
                }
                // validate email address input
                else if(Authenticator.validateEmail(emailTF.getText()) == false) {
                    // display error message
                    JOptionPane.showMessageDialog( null, "Please input a valid Email address!", "Add New Staff Error - Street Sparkle", JOptionPane.WARNING_MESSAGE );
                }
                // record new staff details to database
                else {                    
                    aStaff.setStaffId(); // set the staff SN
                    String staffId = aStaff.getStaffId(); // get the set SN
                    database.addStaff(staffId, usernameTF.getText(), passwordPF.getText(), fNameTF.getText(), midNameTF.getText(), surNameTF.getText(), 
                            staffGender, Integer.parseInt(idTF.getText()), birthDateTF.getText(), Integer.parseInt(phoneTF.getText()), emailTF.getText(),
                            addressTF.getText(), staffCounty, staffTitle, salary, perks, personalDetailsSaveButton);
                    staffIDTF.setText(staffId);
                }
                
            } catch(DateTimeParseException e) {
                // display error message
                JOptionPane.showMessageDialog( null, "Please input valid Date!", "Add New Staff Error - Street Sparkle", JOptionPane.WARNING_MESSAGE );
            }     
        } // end outer else
    }//GEN-LAST:event_personalDetailsSaveButtonHandler

    private void componentHiddenHandler(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_componentHiddenHandler
        // close database connection
        //database.closeDB();
    }//GEN-LAST:event_componentHiddenHandler


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressTF;
    private javax.swing.JTextField birthDateTF;
    private javax.swing.JComboBox<String> countyCB;
    private javax.swing.JTextField emailTF;
    private javax.swing.JTextField fNameTF;
    private javax.swing.JComboBox<String> genderCB;
    private javax.swing.JTextField idTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField midNameTF;
    private javax.swing.JPasswordField passwordPF;
    private javax.swing.JFormattedTextField perksFormattedTF;
    private javax.swing.JButton personalDetailsClearButton;
    private javax.swing.JButton personalDetailsSaveButton;
    private javax.swing.JTextField phoneTF;
    private javax.swing.JPanel registerStaffPanel;
    private javax.swing.JFormattedTextField salaryFormattedTF;
    private javax.swing.JTextField staffIDTF;
    private javax.swing.JTextField surNameTF;
    private javax.swing.JComboBox<String> titleCB;
    private javax.swing.JTextField usernameTF;
    // End of variables declaration//GEN-END:variables
}
