/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package streetSparkle;

import java.awt.CardLayout;
import java.awt.Color;

/**
 *
 * @author John Felix
 */
public class HumanResourceUI extends javax.swing.JFrame {

    public Database database; // class obj
    public Staff aStaff; // class obj
    
    public CardLayout cardLayout; // layout manager for changing panels on button click
    public HRregisterStaffPanel regStaffPanel; // panel obj
    public HRreportsPanel reportsPanel; // panel obj
    public UserProfilePanel profilePanel; // panel obj
    
    /**
     * Creates new form HumanResourceUI
     */
    public HumanResourceUI() {
        /* variable instatiation */
        aStaff = new Staff();
        database = new Database();
        cardLayout = new CardLayout();
        regStaffPanel = new HRregisterStaffPanel();
        reportsPanel = new HRreportsPanel();
        profilePanel = new UserProfilePanel();
        
        initComponents(); // method invokation to set GUI components
        
        HRmainPanel.setLayout(cardLayout);
        HRmainPanel.add(regStaffPanel,"panel1"); // add panel obj for register staff button click
        HRmainPanel.add(reportsPanel,"panel2"); // add panel obj for reports button click
        HRmainPanel.add(profilePanel,"panel3"); // add panel obj for profile button click
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HRframePanel = new javax.swing.JPanel();
        HRnavigationPanel = new javax.swing.JPanel();
        NavigationRegisterStaffButton = new javax.swing.JButton();
        NavigationReportsButton = new javax.swing.JButton();
        NavigationProfileButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        HRmainPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Human Resource - Street Sparkle");
        setBackground(new java.awt.Color(255, 255, 255));
        setExtendedState(6);
        setMinimumSize(new java.awt.Dimension(1350, 700));
        setPreferredSize(new java.awt.Dimension(1375, 801));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                windowClosingHandler(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                windowOpenedHandler(evt);
            }
        });

        HRframePanel.setBackground(new java.awt.Color(255, 255, 255));
        HRframePanel.setPreferredSize(new java.awt.Dimension(1375, 801));
        HRframePanel.setRequestFocusEnabled(false);

        HRnavigationPanel.setBackground(new java.awt.Color(255, 153, 255));
        HRnavigationPanel.setPreferredSize(new java.awt.Dimension(200, 801));

        NavigationRegisterStaffButton.setBackground(new java.awt.Color(255, 153, 255));
        NavigationRegisterStaffButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        NavigationRegisterStaffButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Icons/user-add.png"))); // NOI18N
        NavigationRegisterStaffButton.setText("Register Staff");
        NavigationRegisterStaffButton.setToolTipText("click to register new staff");
        NavigationRegisterStaffButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 255), 3));
        NavigationRegisterStaffButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        NavigationRegisterStaffButton.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                NavigationButtonFocusGainedHandler(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                NavigationButtonFocusLostHandler(evt);
            }
        });
        NavigationRegisterStaffButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NavigationRegisterStaffButtonHandler(evt);
            }
        });

        NavigationReportsButton.setBackground(new java.awt.Color(255, 153, 255));
        NavigationReportsButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        NavigationReportsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Icons/chart-histogram.png"))); // NOI18N
        NavigationReportsButton.setText("Reports");
        NavigationReportsButton.setToolTipText("click to view reports");
        NavigationReportsButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 255), 3));
        NavigationReportsButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        NavigationReportsButton.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                NavigationButtonFocusGainedHandler(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                NavigationButtonFocusLostHandler(evt);
            }
        });
        NavigationReportsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NavigationReportsButtonHandler(evt);
            }
        });

        NavigationProfileButton.setBackground(new java.awt.Color(255, 153, 255));
        NavigationProfileButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        NavigationProfileButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Icons/user.png"))); // NOI18N
        NavigationProfileButton.setText("Profile");
        NavigationProfileButton.setToolTipText("click to view your profile");
        NavigationProfileButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 255), 3));
        NavigationProfileButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        NavigationProfileButton.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                NavigationButtonFocusGainedHandler(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                NavigationButtonFocusLostHandler(evt);
            }
        });
        NavigationProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NavigationProfileButtonHandler(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Viner Hand ITC", 1, 18)); // NOI18N
        jLabel1.setText("HR Management");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout HRnavigationPanelLayout = new javax.swing.GroupLayout(HRnavigationPanel);
        HRnavigationPanel.setLayout(HRnavigationPanelLayout);
        HRnavigationPanelLayout.setHorizontalGroup(
            HRnavigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NavigationRegisterStaffButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(NavigationReportsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(NavigationProfileButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(HRnavigationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                .addContainerGap())
        );
        HRnavigationPanelLayout.setVerticalGroup(
            HRnavigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HRnavigationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(186, 186, 186)
                .addComponent(NavigationRegisterStaffButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(NavigationReportsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(NavigationProfileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(309, Short.MAX_VALUE))
        );

        HRmainPanel.setBackground(new java.awt.Color(255, 236, 252));

        javax.swing.GroupLayout HRmainPanelLayout = new javax.swing.GroupLayout(HRmainPanel);
        HRmainPanel.setLayout(HRmainPanelLayout);
        HRmainPanelLayout.setHorizontalGroup(
            HRmainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1177, Short.MAX_VALUE)
        );
        HRmainPanelLayout.setVerticalGroup(
            HRmainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout HRframePanelLayout = new javax.swing.GroupLayout(HRframePanel);
        HRframePanel.setLayout(HRframePanelLayout);
        HRframePanelLayout.setHorizontalGroup(
            HRframePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HRframePanelLayout.createSequentialGroup()
                .addComponent(HRnavigationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(HRmainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        HRframePanelLayout.setVerticalGroup(
            HRframePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HRframePanelLayout.createSequentialGroup()
                .addGroup(HRframePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HRnavigationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HRmainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HRframePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1383, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HRframePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void windowOpenedHandler(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_windowOpenedHandler
        // set window size to fullscreen when window is opened
        this.setExtendedState(HumanResourceUI.MAXIMIZED_BOTH); 
    }//GEN-LAST:event_windowOpenedHandler

    private void NavigationButtonFocusGainedHandler(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NavigationButtonFocusGainedHandler
        // change colour on focus
        if(evt.getSource() == NavigationRegisterStaffButton) {
            NavigationRegisterStaffButton.setBackground(new Color(153,255,153));
        }
        else if(evt.getSource() == NavigationReportsButton) {
            NavigationReportsButton.setBackground(new Color(153,255,153));
        }
        else if(evt.getSource() == NavigationProfileButton) {
            NavigationProfileButton.setBackground(new Color(153,255,153));
        }
    }//GEN-LAST:event_NavigationButtonFocusGainedHandler

    private void NavigationButtonFocusLostHandler(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NavigationButtonFocusLostHandler
        // change colour on losing focus
        if(evt.getSource() == NavigationRegisterStaffButton) {
            NavigationRegisterStaffButton.setBackground(new Color(255, 153, 255));
        }
        else if(evt.getSource() == NavigationReportsButton) {
            NavigationReportsButton.setBackground(new Color(255, 153, 255));
        }
        else if(evt.getSource() == NavigationProfileButton) {
            NavigationProfileButton.setBackground(new Color(255, 153, 255));
        }
    }//GEN-LAST:event_NavigationButtonFocusLostHandler

    private void NavigationRegisterStaffButtonHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NavigationRegisterStaffButtonHandler
        // display panel1
        cardLayout.show(HRmainPanel,"panel1");
    }//GEN-LAST:event_NavigationRegisterStaffButtonHandler

    private void NavigationReportsButtonHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NavigationReportsButtonHandler
        // display panel2
        cardLayout.show(HRmainPanel,"panel2");
    }//GEN-LAST:event_NavigationReportsButtonHandler

    private void NavigationProfileButtonHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NavigationProfileButtonHandler
        // display panel3
        cardLayout.show(HRmainPanel,"panel3");
    }//GEN-LAST:event_NavigationProfileButtonHandler

    private void windowClosingHandler(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_windowClosingHandler
        // close database connection then exit
        database.closeDB();
        System.exit(0);
    }//GEN-LAST:event_windowClosingHandler

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HumanResourceUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HumanResourceUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HumanResourceUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HumanResourceUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HumanResourceUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel HRframePanel;
    private javax.swing.JPanel HRmainPanel;
    private javax.swing.JPanel HRnavigationPanel;
    private javax.swing.JButton NavigationProfileButton;
    private javax.swing.JButton NavigationRegisterStaffButton;
    private javax.swing.JButton NavigationReportsButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
