/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package streetSparkle;

import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.event.HyperlinkEvent;

/**
 *
 * @author John Felix
 */
public class MapsPanel extends javax.swing.JPanel {

    /**
     * Creates new form MapsPanel
     */
    public MapsPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mapsMainPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mapsEditorPane = new javax.swing.JEditorPane();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                componentShownHandler(evt);
            }
        });

        mapsMainPanel.setBackground(new java.awt.Color(249, 251, 253));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(64, 4));

        mapsEditorPane.setContentType("text/html"); // NOI18N
        mapsEditorPane.setPreferredSize(new java.awt.Dimension(62, 2));
        mapsEditorPane.addHyperlinkListener(new javax.swing.event.HyperlinkListener() {
            public void hyperlinkUpdate(javax.swing.event.HyperlinkEvent evt) {
                hyperlinkUpdateHandler(evt);
            }
        });
        mapsEditorPane.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                componentHiddenHandler(evt);
            }
        });
        jScrollPane1.setViewportView(mapsEditorPane);

        javax.swing.GroupLayout mapsMainPanelLayout = new javax.swing.GroupLayout(mapsMainPanel);
        mapsMainPanel.setLayout(mapsMainPanelLayout);
        mapsMainPanelLayout.setHorizontalGroup(
            mapsMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mapsMainPanelLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        mapsMainPanelLayout.setVerticalGroup(
            mapsMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mapsMainPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 671, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mapsMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mapsMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void componentShownHandler(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_componentShownHandler
        // load Google Maps to editor pane
        try {
            mapsEditorPane.setPage("https://www.google.com/maps/@-1.2447093,36.883201,15z?hl=en");
        } catch(IOException e) {
            // displaying of url error message 
            JOptionPane.showMessageDialog( null, "Error retrieving specified URL!", "Maps Error", JOptionPane.ERROR_MESSAGE );
            String err = "<h2>Unable to connect:<br>Check your internet connection and reload!</h2>";
            mapsEditorPane.setText(err);
        }
    }//GEN-LAST:event_componentShownHandler

    private void hyperlinkUpdateHandler(javax.swing.event.HyperlinkEvent evt) {//GEN-FIRST:event_hyperlinkUpdateHandler
        // if user clicks hyperlink, go to specified page
        if(evt.getEventType() == HyperlinkEvent.EventType.ACTIVATED) {
            try {
                // load the document
                mapsEditorPane.setPage(evt.getURL().toString());
            } catch(IOException e) {
                // displaying of hyperlink error message 
                JOptionPane.showMessageDialog( null, "Error retrieving specified URL!", "Maps Error", JOptionPane.ERROR_MESSAGE );
            }
        }
    }//GEN-LAST:event_hyperlinkUpdateHandler

    private void componentHiddenHandler(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_componentHiddenHandler
        // clear editor pane
        mapsEditorPane.setText("");
    }//GEN-LAST:event_componentHiddenHandler


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JEditorPane mapsEditorPane;
    private javax.swing.JPanel mapsMainPanel;
    // End of variables declaration//GEN-END:variables
}
