/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package streetSparkle;

import java.awt.CardLayout;
import java.awt.Color;

/**
 *
 * @author John Felix
 */
public class SalesUI extends javax.swing.JFrame {

    public CardLayout cardLayout; // layout manager for changing panels on button click
    public MapsPanel mapPanel; // panel obj
    public UserProfilePanel profilePanel; // panel obj
    public SalesProjectPanel projectPanel; // panel obj
    public SalesReportPanel reportsPanel; // panel obj
    public SalesRegisterationPanel registerPanel; // panel obj
    
    /**
     * Creates new form SalesUI
     */
    public SalesUI() {
        /* variable instatiation */
        cardLayout = new CardLayout();
        mapPanel = new MapsPanel();
        profilePanel = new UserProfilePanel();
        projectPanel = new SalesProjectPanel();
        reportsPanel = new SalesReportPanel();
        registerPanel = new SalesRegisterationPanel();
        
        initComponents(); // method invokation to set GUI components
        
        salesMainPanel.setLayout(cardLayout);
        salesMainPanel.add(registerPanel,"panel1"); // add panel obj for registeration button click
        salesMainPanel.add(projectPanel,"panel2"); // add panel obj for register project button click        
        salesMainPanel.add(mapPanel,"panel3"); // add panel obj for maps button click
        salesMainPanel.add(reportsPanel,"panel4"); // add panel obj for reports button click
        salesMainPanel.add(profilePanel,"panel5"); // add panel obj for profile button click
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        salesFramePanel = new javax.swing.JPanel();
        salesNavigationPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        navRegProjectButton = new javax.swing.JButton();
        navMapsButton = new javax.swing.JButton();
        navReportsButton = new javax.swing.JButton();
        navProfileButton = new javax.swing.JButton();
        navRegisterationButton = new javax.swing.JButton();
        salesMainPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sales & Finance - Street Sparkle");
        setExtendedState(6);
        setMinimumSize(new java.awt.Dimension(1350, 700));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                windowOpenedHandler(evt);
            }
        });

        salesFramePanel.setBackground(new java.awt.Color(255, 255, 255));

        salesNavigationPanel.setBackground(new java.awt.Color(0, 153, 5));

        jLabel1.setFont(new java.awt.Font("Viner Hand ITC", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sales & Finance");

        navRegProjectButton.setBackground(new java.awt.Color(0, 153, 5));
        navRegProjectButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        navRegProjectButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Icons/broom(1).png"))); // NOI18N
        navRegProjectButton.setText("Register Project");
        navRegProjectButton.setToolTipText("click to register a new project");
        navRegProjectButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 5), 3));
        navRegProjectButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        navRegProjectButton.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                navigationButtonFocusGainedHandler(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                navigationButtonFocusLostHandler(evt);
            }
        });
        navRegProjectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navRegProjectButtonHandler(evt);
            }
        });

        navMapsButton.setBackground(new java.awt.Color(0, 153, 5));
        navMapsButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        navMapsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Icons/map-marker(1).png"))); // NOI18N
        navMapsButton.setText("Maps");
        navMapsButton.setToolTipText("click to view google maps");
        navMapsButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 5), 3));
        navMapsButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        navMapsButton.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                navigationButtonFocusGainedHandler(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                navigationButtonFocusLostHandler(evt);
            }
        });
        navMapsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navMapsButtonHandler(evt);
            }
        });

        navReportsButton.setBackground(new java.awt.Color(0, 153, 5));
        navReportsButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        navReportsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Icons/chart-histogram.png"))); // NOI18N
        navReportsButton.setText("Reports");
        navReportsButton.setToolTipText("click to view reports");
        navReportsButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 5), 3));
        navReportsButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        navReportsButton.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                navigationButtonFocusGainedHandler(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                navigationButtonFocusLostHandler(evt);
            }
        });
        navReportsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navReportsButtonHandler(evt);
            }
        });

        navProfileButton.setBackground(new java.awt.Color(0, 153, 5));
        navProfileButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        navProfileButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Icons/user.png"))); // NOI18N
        navProfileButton.setText("Profile");
        navProfileButton.setToolTipText("click to view your profile");
        navProfileButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 5), 3));
        navProfileButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        navProfileButton.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                navigationButtonFocusGainedHandler(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                navigationButtonFocusLostHandler(evt);
            }
        });
        navProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navProfileButtonHandler(evt);
            }
        });

        navRegisterationButton.setBackground(new java.awt.Color(0, 153, 5));
        navRegisterationButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        navRegisterationButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Icons/user-add.png"))); // NOI18N
        navRegisterationButton.setText("Registration ");
        navRegisterationButton.setToolTipText("click to register new client & supplier");
        navRegisterationButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 5), 3));
        navRegisterationButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        navRegisterationButton.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                navigationButtonFocusGainedHandler(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                navigationButtonFocusLostHandler(evt);
            }
        });
        navRegisterationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navRegisterationButtonHandler(evt);
            }
        });

        javax.swing.GroupLayout salesNavigationPanelLayout = new javax.swing.GroupLayout(salesNavigationPanel);
        salesNavigationPanel.setLayout(salesNavigationPanelLayout);
        salesNavigationPanelLayout.setHorizontalGroup(
            salesNavigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salesNavigationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(navRegProjectButton, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
            .addComponent(navMapsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(navReportsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(navProfileButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(navRegisterationButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        salesNavigationPanelLayout.setVerticalGroup(
            salesNavigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salesNavigationPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addComponent(navRegisterationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(navRegProjectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(navMapsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(navReportsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(navProfileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(307, Short.MAX_VALUE))
        );

        salesMainPanel.setBackground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout salesMainPanelLayout = new javax.swing.GroupLayout(salesMainPanel);
        salesMainPanel.setLayout(salesMainPanelLayout);
        salesMainPanelLayout.setHorizontalGroup(
            salesMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1120, Short.MAX_VALUE)
        );
        salesMainPanelLayout.setVerticalGroup(
            salesMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 801, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout salesFramePanelLayout = new javax.swing.GroupLayout(salesFramePanel);
        salesFramePanel.setLayout(salesFramePanelLayout);
        salesFramePanelLayout.setHorizontalGroup(
            salesFramePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salesFramePanelLayout.createSequentialGroup()
                .addComponent(salesNavigationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(salesMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        salesFramePanelLayout.setVerticalGroup(
            salesFramePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(salesMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(salesNavigationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(salesFramePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(salesFramePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void windowOpenedHandler(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_windowOpenedHandler
        // set window size to fullscreen when window is opened
        this.setExtendedState(SalesUI.MAXIMIZED_BOTH); 
    }//GEN-LAST:event_windowOpenedHandler

    private void navigationButtonFocusGainedHandler(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_navigationButtonFocusGainedHandler
        // change colour on focus
        if(evt.getSource() == navRegProjectButton) {
           navRegProjectButton.setBackground(new Color(255,255,255));
        }
        else if(evt.getSource() == navRegisterationButton) {
           navRegisterationButton.setBackground(new Color(255,255,255)); 
        }
        else if(evt.getSource() == navMapsButton) {
           navMapsButton.setBackground(new Color(255,255,255)); 
        }
        else if(evt.getSource() == navReportsButton) {
           navReportsButton.setBackground(new Color(255,255,255)); 
        }
        else if(evt.getSource() == navProfileButton) {
           navProfileButton.setBackground(new Color(255,255,255)); 
        }
    }//GEN-LAST:event_navigationButtonFocusGainedHandler

    private void navigationButtonFocusLostHandler(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_navigationButtonFocusLostHandler
        // change colour on focus lost
        if(evt.getSource() == navRegProjectButton) {
           navRegProjectButton.setBackground(new Color(0,153,5));
        }
        else if(evt.getSource() == navRegisterationButton) {
           navRegisterationButton.setBackground(new Color(0,153,5)); 
        }
        else if(evt.getSource() == navMapsButton) {
           navMapsButton.setBackground(new Color(0,153,5)); 
        }
        else if(evt.getSource() == navReportsButton) {
           navReportsButton.setBackground(new Color(0,153,5)); 
        }
        else if(evt.getSource() == navProfileButton) {
           navProfileButton.setBackground(new Color(0,153,5)); 
        }
    }//GEN-LAST:event_navigationButtonFocusLostHandler

    private void navRegProjectButtonHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navRegProjectButtonHandler
        // display panel2
        cardLayout.show(salesMainPanel,"panel2");
    }//GEN-LAST:event_navRegProjectButtonHandler

    private void navRegisterationButtonHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navRegisterationButtonHandler
        // display panel1
        cardLayout.show(salesMainPanel,"panel1");
    }//GEN-LAST:event_navRegisterationButtonHandler

    private void navMapsButtonHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navMapsButtonHandler
        // display panel3
        cardLayout.show(salesMainPanel,"panel3");
    }//GEN-LAST:event_navMapsButtonHandler

    private void navReportsButtonHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navReportsButtonHandler
        // display panel4
        cardLayout.show(salesMainPanel,"panel4");
    }//GEN-LAST:event_navReportsButtonHandler

    private void navProfileButtonHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navProfileButtonHandler
        // display panel5
        cardLayout.show(salesMainPanel,"panel5");
    }//GEN-LAST:event_navProfileButtonHandler

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalesUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalesUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalesUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalesUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalesUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton navMapsButton;
    private javax.swing.JButton navProfileButton;
    private javax.swing.JButton navRegProjectButton;
    private javax.swing.JButton navRegisterationButton;
    private javax.swing.JButton navReportsButton;
    private javax.swing.JPanel salesFramePanel;
    private javax.swing.JPanel salesMainPanel;
    private javax.swing.JPanel salesNavigationPanel;
    // End of variables declaration//GEN-END:variables
}
