/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package streetSparkle;

import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.plaf.metal.MetalLookAndFeel;
import javax.swing.plaf.metal.OceanTheme;

/**
 *
 * @author John Felix
 */
public class SupervisorUI extends javax.swing.JFrame {

    public Database database; // class obj
    public CardLayout cardLayout; // layout manager for changing panels on button click
    public SUPregisterCasualPanel regCasualPanel; // panel obj
    public SUPprojectsPanel projectsPanel; // panel obj
    public MapsPanel mapsPanel; // panel obj
    public UserProfilePanel profilePanel; // panel obj
    public SUPattendancePanel attendancePanel; // panel obj
    public SUPreportsPanel reportsPanel; // panel obj
    public ToolsReportPanel toolReportsPanel; // panel obj
    
    /**
     * Creates new form SupervisorUI
     */
    public SupervisorUI() {
        /* variable instatiation */
        database = new Database();
        cardLayout = new CardLayout();
        regCasualPanel = new SUPregisterCasualPanel();
        projectsPanel = new SUPprojectsPanel();
        mapsPanel = new MapsPanel();
        profilePanel = new UserProfilePanel();
        attendancePanel = new SUPattendancePanel();
        reportsPanel = new SUPreportsPanel();
        toolReportsPanel = new ToolsReportPanel();
        
        initComponents(); // method invokation to set GUI components
        
        supervisorMainPanel.setLayout(cardLayout);       
        supervisorMainPanel.add(regCasualPanel,"panel1"); // add panel obj for register casual button click
        supervisorMainPanel.add(projectsPanel,"panel2"); // add panel obj for projects button click
        supervisorMainPanel.add(attendancePanel,"panel3"); // add panel obj for attendance button click
        supervisorMainPanel.add(mapsPanel,"panel4"); // add panel obj for maps button click
        supervisorMainPanel.add(toolReportsPanel,"panel5"); // add panel obj for tools button click
        supervisorMainPanel.add(reportsPanel,"panel6"); // add panel obj for reports button click
        supervisorMainPanel.add(profilePanel,"panel7"); // add panel obj for profile button click
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        supervisorFramePanel = new javax.swing.JPanel();
        supervisorNavigationPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        navRegisterCasualButton = new javax.swing.JButton();
        navReportsButton = new javax.swing.JButton();
        navMapsButton = new javax.swing.JButton();
        navToolsButton = new javax.swing.JButton();
        navProjectsButton = new javax.swing.JButton();
        navAttendanceButton = new javax.swing.JButton();
        navsProfileButton = new javax.swing.JButton();
        supervisorMainPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Supervisor Interface - Street Sparkle");
        setExtendedState(6);
        setMinimumSize(new java.awt.Dimension(1350, 700));
        setPreferredSize(new java.awt.Dimension(1375, 801));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                windowClosingHandler(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                windowOpenedHandler(evt);
            }
        });

        supervisorFramePanel.setBackground(new java.awt.Color(216, 235, 254));
        supervisorFramePanel.setPreferredSize(new java.awt.Dimension(1375, 801));

        supervisorNavigationPanel.setBackground(new java.awt.Color(102, 102, 255));
        supervisorNavigationPanel.setPreferredSize(new java.awt.Dimension(201, 801));

        jLabel5.setFont(new java.awt.Font("Viner Hand ITC", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("SUPERVISOR INTERFACE");

        navRegisterCasualButton.setBackground(new java.awt.Color(102, 102, 255));
        navRegisterCasualButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        navRegisterCasualButton.setForeground(new java.awt.Color(255, 255, 255));
        navRegisterCasualButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Icons/user-add.png"))); // NOI18N
        navRegisterCasualButton.setText("Register Casual");
        navRegisterCasualButton.setToolTipText("click to add new casual worker");
        navRegisterCasualButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255), 3));
        navRegisterCasualButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        navRegisterCasualButton.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                navigationButtonFocusGainedHandler(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                navigationButtonFocusLostHandler(evt);
            }
        });
        navRegisterCasualButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navRegisterCasualButton(evt);
            }
        });

        navReportsButton.setBackground(new java.awt.Color(102, 102, 255));
        navReportsButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        navReportsButton.setForeground(new java.awt.Color(255, 255, 255));
        navReportsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Icons/chart-histogram.png"))); // NOI18N
        navReportsButton.setText("Reports");
        navReportsButton.setToolTipText("click to view reports");
        navReportsButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255), 3));
        navReportsButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        navReportsButton.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                navigationButtonFocusGainedHandler(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                navigationButtonFocusLostHandler(evt);
            }
        });
        navReportsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navReportsButtonHandler(evt);
            }
        });

        navMapsButton.setBackground(new java.awt.Color(102, 102, 255));
        navMapsButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        navMapsButton.setForeground(new java.awt.Color(255, 255, 255));
        navMapsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Icons/map-marker(1).png"))); // NOI18N
        navMapsButton.setText("Maps");
        navMapsButton.setToolTipText("click to view maps");
        navMapsButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255), 3));
        navMapsButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        navMapsButton.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                navigationButtonFocusGainedHandler(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                navigationButtonFocusLostHandler(evt);
            }
        });
        navMapsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navMapsButtonHandler(evt);
            }
        });

        navToolsButton.setBackground(new java.awt.Color(102, 102, 255));
        navToolsButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        navToolsButton.setForeground(new java.awt.Color(255, 255, 255));
        navToolsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Icons/wrench-simple(1).png"))); // NOI18N
        navToolsButton.setText("Tools");
        navToolsButton.setToolTipText("click to view tool details");
        navToolsButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255), 3));
        navToolsButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        navToolsButton.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                navigationButtonFocusGainedHandler(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                navigationButtonFocusLostHandler(evt);
            }
        });
        navToolsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navToolsButtonHandler(evt);
            }
        });

        navProjectsButton.setBackground(new java.awt.Color(102, 102, 255));
        navProjectsButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        navProjectsButton.setForeground(new java.awt.Color(255, 255, 255));
        navProjectsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Icons/broom(1).png"))); // NOI18N
        navProjectsButton.setText("Projects");
        navProjectsButton.setToolTipText("click to staff projects");
        navProjectsButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255), 3));
        navProjectsButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        navProjectsButton.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                navigationButtonFocusGainedHandler(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                navigationButtonFocusLostHandler(evt);
            }
        });
        navProjectsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navProjectsButtonHandler(evt);
            }
        });

        navAttendanceButton.setBackground(new java.awt.Color(102, 102, 255));
        navAttendanceButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        navAttendanceButton.setForeground(new java.awt.Color(255, 255, 255));
        navAttendanceButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Icons/people-poll.png"))); // NOI18N
        navAttendanceButton.setText("Attendance");
        navAttendanceButton.setToolTipText("click to register casual worker's attendance");
        navAttendanceButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255), 3));
        navAttendanceButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        navAttendanceButton.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                navigationButtonFocusGainedHandler(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                navigationButtonFocusLostHandler(evt);
            }
        });
        navAttendanceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navAttendanceButtonHandler(evt);
            }
        });

        navsProfileButton.setBackground(new java.awt.Color(102, 102, 255));
        navsProfileButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        navsProfileButton.setForeground(new java.awt.Color(255, 255, 255));
        navsProfileButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Icons/user.png"))); // NOI18N
        navsProfileButton.setText("Profile");
        navsProfileButton.setToolTipText("click to view your profile");
        navsProfileButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255), 3));
        navsProfileButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        navsProfileButton.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                navigationButtonFocusGainedHandler(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                navigationButtonFocusLostHandler(evt);
            }
        });
        navsProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navsProfileButtonHandler(evt);
            }
        });

        javax.swing.GroupLayout supervisorNavigationPanelLayout = new javax.swing.GroupLayout(supervisorNavigationPanel);
        supervisorNavigationPanel.setLayout(supervisorNavigationPanelLayout);
        supervisorNavigationPanelLayout.setHorizontalGroup(
            supervisorNavigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(supervisorNavigationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(navRegisterCasualButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(navReportsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(navMapsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(navToolsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(navProjectsButton, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
            .addComponent(navAttendanceButton, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
            .addComponent(navsProfileButton, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
        );
        supervisorNavigationPanelLayout.setVerticalGroup(
            supervisorNavigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(supervisorNavigationPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addComponent(navRegisterCasualButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(navProjectsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(navAttendanceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(navMapsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(navToolsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(navReportsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(navsProfileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        supervisorMainPanel.setBackground(new java.awt.Color(216, 235, 254));
        supervisorMainPanel.setPreferredSize(new java.awt.Dimension(1150, 700));

        javax.swing.GroupLayout supervisorMainPanelLayout = new javax.swing.GroupLayout(supervisorMainPanel);
        supervisorMainPanel.setLayout(supervisorMainPanelLayout);
        supervisorMainPanelLayout.setHorizontalGroup(
            supervisorMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1192, Short.MAX_VALUE)
        );
        supervisorMainPanelLayout.setVerticalGroup(
            supervisorMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 813, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout supervisorFramePanelLayout = new javax.swing.GroupLayout(supervisorFramePanel);
        supervisorFramePanel.setLayout(supervisorFramePanelLayout);
        supervisorFramePanelLayout.setHorizontalGroup(
            supervisorFramePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(supervisorFramePanelLayout.createSequentialGroup()
                .addComponent(supervisorNavigationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(supervisorMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1192, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        supervisorFramePanelLayout.setVerticalGroup(
            supervisorFramePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(supervisorNavigationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 813, Short.MAX_VALUE)
            .addComponent(supervisorMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 813, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(supervisorFramePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1393, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(supervisorFramePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 813, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void windowOpenedHandler(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_windowOpenedHandler
        // set window size to fullscreen when window is opened
        this.setExtendedState(SupervisorUI.MAXIMIZED_BOTH); 
    }//GEN-LAST:event_windowOpenedHandler

    private void navigationButtonFocusGainedHandler(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_navigationButtonFocusGainedHandler
        // change colour on focus
        if(evt.getSource() == navRegisterCasualButton) {
            navRegisterCasualButton.setBackground(new Color(255,255,255));
            navRegisterCasualButton.setForeground(new Color(0,0,0));
        }
        else if(evt.getSource() == navReportsButton) {
            navReportsButton.setBackground(new Color(255,255,255));
            navReportsButton.setForeground(new Color(0,0,0));
        }
        else if(evt.getSource() == navMapsButton) {
            navMapsButton.setBackground(new Color(255,255,255));
            navMapsButton.setForeground(new Color(0,0,0));
        }
        else if(evt.getSource() == navsProfileButton) {
            navsProfileButton.setBackground(new Color(255,255,255));
            navsProfileButton.setForeground(new Color(0,0,0));
        }
        else if(evt.getSource() == navAttendanceButton) {
            navAttendanceButton.setBackground(new Color(255,255,255));
            navAttendanceButton.setForeground(new Color(0,0,0));
        }
        else if(evt.getSource() == navToolsButton) {
            navToolsButton.setBackground(new Color(255,255,255));
            navToolsButton.setForeground(new Color(0,0,0));
        }
        else if(evt.getSource() == navProjectsButton) {
            navProjectsButton.setBackground(new Color(255,255,255));
            navProjectsButton.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_navigationButtonFocusGainedHandler

    private void navigationButtonFocusLostHandler(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_navigationButtonFocusLostHandler
        // change colour on focus lost
        if(evt.getSource() == navRegisterCasualButton) {
            navRegisterCasualButton.setBackground(new Color(102,102,255));
            navRegisterCasualButton.setForeground(new Color(255,255,255));
        }
        else if(evt.getSource() == navReportsButton) {
            navReportsButton.setBackground(new Color(102,102,255));
            navReportsButton.setForeground(new Color(255,255,255));
        }
        else if(evt.getSource() == navMapsButton) {
            navMapsButton.setBackground(new Color(102,102,255));
            navMapsButton.setForeground(new Color(255,255,255));
        }
        else if(evt.getSource() == navsProfileButton) {
            navsProfileButton.setBackground(new Color(102,102,255));
            navsProfileButton.setForeground(new Color(255,255,255));
        }
        else if(evt.getSource() == navAttendanceButton) {
            navAttendanceButton.setBackground(new Color(102,102,255));
            navAttendanceButton.setForeground(new Color(255,255,255));
        }
        else if(evt.getSource() == navToolsButton) {
            navToolsButton.setBackground(new Color(102,102,255));
            navToolsButton.setForeground(new Color(255,255,255));
        }
        else if(evt.getSource() == navProjectsButton) {
            navProjectsButton.setBackground(new Color(102,102,255));
            navProjectsButton.setForeground(new Color(255,255,255));
        }
    }//GEN-LAST:event_navigationButtonFocusLostHandler

    private void navMapsButtonHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navMapsButtonHandler
        // display panel4
        cardLayout.show(supervisorMainPanel,"panel4");
    }//GEN-LAST:event_navMapsButtonHandler

    private void navsProfileButtonHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navsProfileButtonHandler
        // display panel7
        cardLayout.show(supervisorMainPanel,"panel7");
    }//GEN-LAST:event_navsProfileButtonHandler

    private void navAttendanceButtonHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navAttendanceButtonHandler
        // display panel3
        cardLayout.show(supervisorMainPanel,"panel3");
    }//GEN-LAST:event_navAttendanceButtonHandler

    private void navRegisterCasualButton(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navRegisterCasualButton
        // display panel1
        cardLayout.show(supervisorMainPanel,"panel1");
    }//GEN-LAST:event_navRegisterCasualButton

    private void navReportsButtonHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navReportsButtonHandler
        // display panel6
        cardLayout.show(supervisorMainPanel,"panel6");
    }//GEN-LAST:event_navReportsButtonHandler

    private void navToolsButtonHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navToolsButtonHandler
        // display panel5
        cardLayout.show(supervisorMainPanel,"panel5");
    }//GEN-LAST:event_navToolsButtonHandler

    private void navProjectsButtonHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navProjectsButtonHandler
        // display panel2
        cardLayout.show(supervisorMainPanel,"panel2");
    }//GEN-LAST:event_navProjectsButtonHandler

    private void windowClosingHandler(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_windowClosingHandler
        // close database connection then exit
        database.closeDB();
        System.exit(0);
    }//GEN-LAST:event_windowClosingHandler

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    MetalLookAndFeel.setCurrentTheme(new OceanTheme());
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SupervisorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SupervisorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SupervisorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SupervisorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SupervisorUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton navAttendanceButton;
    private javax.swing.JButton navMapsButton;
    private javax.swing.JButton navProjectsButton;
    private javax.swing.JButton navRegisterCasualButton;
    private javax.swing.JButton navReportsButton;
    private javax.swing.JButton navToolsButton;
    private javax.swing.JButton navsProfileButton;
    private javax.swing.JPanel supervisorFramePanel;
    private javax.swing.JPanel supervisorMainPanel;
    private javax.swing.JPanel supervisorNavigationPanel;
    // End of variables declaration//GEN-END:variables
}
