/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package streetSparkle;

import java.time.format.DateTimeParseException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author John Felix
 */
public class ToolsPanel extends javax.swing.JPanel {
    
    public Database database; // class obj
    public Tools aTool; // class obj

    /**
     * Creates new form ToolsPanel
     */
    public ToolsPanel() {
        /* variable instantiation */
        database = new Database();
        aTool = new Tools();
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        toolsMainPanel1 = new javax.swing.JPanel();
        toolsTabbedPane1 = new javax.swing.JTabbedPane();
        registerTabPanel1 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        toolNameTF = new javax.swing.JTextField();
        toolBuyQtyTF = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        toolBuyDateTF = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        toolBuyPriceFormattedTF = new javax.swing.JFormattedTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        toolDescriptionTextArea = new javax.swing.JTextArea();
        toolSizeComboBox = new javax.swing.JComboBox<>();
        toolSaveButton = new javax.swing.JButton();
        toolClearButton = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        borrowTabPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        borrowTable = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        staffIdBorrowTF = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        goodQtyBorrowTF = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        damageQtyBorrowTF = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        durationBorrowTF = new javax.swing.JTextField();
        borrowResetButton = new javax.swing.JButton();
        borrowSubmitButton = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        returnTabPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        staffIdSearchTF = new javax.swing.JTextField();
        searchBorrowButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        returnTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        submitGoodButton = new javax.swing.JButton();
        resetGoodButton = new javax.swing.JButton();
        damageReturnPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        damageSnTF = new javax.swing.JTextField();
        damageQtyReturnTF = new javax.swing.JTextField();
        damageUnderTF = new javax.swing.JTextField();
        submitDamageButton = new javax.swing.JButton();
        clearDamageButton = new javax.swing.JButton();
        LostReturnPanel = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lostSnTF = new javax.swing.JTextField();
        lostQtyReturnTF = new javax.swing.JTextField();
        lostUnderTF = new javax.swing.JTextField();
        submitLostButton = new javax.swing.JButton();
        clearLostButton = new javax.swing.JButton();
        goodQtyReturnTF = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 244, 214));
        setPreferredSize(new java.awt.Dimension(1150, 700));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                componentHiddenHandler(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 244, 214));
        jPanel1.setPreferredSize(new java.awt.Dimension(1150, 700));

        toolsMainPanel1.setBackground(new java.awt.Color(255, 244, 214));
        toolsMainPanel1.setPreferredSize(new java.awt.Dimension(1150, 700));

        toolsTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        toolsTabbedPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255), 2));
        toolsTabbedPane1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        toolsTabbedPane1.setPreferredSize(new java.awt.Dimension(1138, 690));
        toolsTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mouseClickedHandler(evt);
            }
        });
        toolsTabbedPane1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numericKeyTypedHandler(evt);
            }
        });

        registerTabPanel1.setBackground(new java.awt.Color(249, 251, 253));

        jLabel16.setFont(new java.awt.Font("News706 BT", 0, 14)); // NOI18N
        jLabel16.setLabelFor(toolNameTF);
        jLabel16.setText("Tool Name");

        toolNameTF.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        toolBuyQtyTF.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        toolBuyQtyTF.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        toolBuyQtyTF.setText("0");
        toolBuyQtyTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numericKeyTypedHandler(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("News706 BT", 0, 14)); // NOI18N
        jLabel17.setLabelFor(toolBuyQtyTF);
        jLabel17.setText("Buy Quantity");

        jLabel18.setFont(new java.awt.Font("News706 BT", 0, 14)); // NOI18N
        jLabel18.setLabelFor(toolBuyDateTF);
        jLabel18.setText("Buy Date");

        toolBuyDateTF.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        toolBuyDateTF.setText("YYYY-MM-DD");

        jLabel19.setFont(new java.awt.Font("News706 BT", 0, 14)); // NOI18N
        jLabel19.setLabelFor(toolSizeComboBox);
        jLabel19.setText("Tool Size");

        jLabel20.setFont(new java.awt.Font("News706 BT", 0, 14)); // NOI18N
        jLabel20.setLabelFor(toolBuyPriceFormattedTF);
        jLabel20.setText("Buy Price");

        toolBuyPriceFormattedTF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        toolBuyPriceFormattedTF.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        toolBuyPriceFormattedTF.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jScrollPane3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Tool Description", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Monospaced", 1, 14))); // NOI18N

        toolDescriptionTextArea.setColumns(20);
        toolDescriptionTextArea.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        toolDescriptionTextArea.setLineWrap(true);
        toolDescriptionTextArea.setRows(5);
        toolDescriptionTextArea.setToolTipText("fill in the tool's description");
        jScrollPane3.setViewportView(toolDescriptionTextArea);

        toolSizeComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        toolSizeComboBox.setMaximumRowCount(3);
        toolSizeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SMALL", "MEDIUM", "LARGE" }));

        toolSaveButton.setBackground(new java.awt.Color(255, 0, 255));
        toolSaveButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        toolSaveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Icons/folder-download.png"))); // NOI18N
        toolSaveButton.setText("Save");
        toolSaveButton.setToolTipText("click to save the tool details");
        toolSaveButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        toolSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toolSaveButtonHandler(evt);
            }
        });

        toolClearButton.setBackground(new java.awt.Color(255, 0, 255));
        toolClearButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        toolClearButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Icons/delete.png"))); // NOI18N
        toolClearButton.setText("Clear");
        toolClearButton.setToolTipText("click to clear the fields");
        toolClearButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        toolClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toolClearButtonHandler(evt);
            }
        });

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Images/image4.jpeg"))); // NOI18N

        javax.swing.GroupLayout registerTabPanel1Layout = new javax.swing.GroupLayout(registerTabPanel1);
        registerTabPanel1.setLayout(registerTabPanel1Layout);
        registerTabPanel1Layout.setHorizontalGroup(
            registerTabPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerTabPanel1Layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addGroup(registerTabPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registerTabPanel1Layout.createSequentialGroup()
                        .addGroup(registerTabPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(registerTabPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(toolNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(registerTabPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(toolBuyQtyTF, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(registerTabPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(toolBuyDateTF, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(141, 141, 141)
                        .addGroup(registerTabPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(registerTabPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(toolBuyPriceFormattedTF, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3))
                        .addContainerGap(136, Short.MAX_VALUE))
                    .addGroup(registerTabPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(registerTabPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(registerTabPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(toolClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(registerTabPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(toolSizeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerTabPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(registerTabPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerTabPanel1Layout.createSequentialGroup()
                        .addComponent(toolSaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(263, 263, 263))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerTabPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(352, 352, 352))))
        );
        registerTabPanel1Layout.setVerticalGroup(
            registerTabPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerTabPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(registerTabPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(toolBuyPriceFormattedTF)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(toolNameTF, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                .addGap(50, 50, 50)
                .addGroup(registerTabPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registerTabPanel1Layout.createSequentialGroup()
                        .addGroup(registerTabPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(toolBuyQtyTF))
                        .addGap(50, 50, 50)
                        .addGroup(registerTabPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(toolBuyDateTF))
                        .addGap(50, 50, 50)
                        .addGroup(registerTabPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                            .addComponent(toolSizeComboBox)))
                    .addComponent(jScrollPane3))
                .addGap(32, 32, 32)
                .addGroup(registerTabPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(toolSaveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(toolClearButton, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        toolsTabbedPane1.addTab("Register Tool  ", new javax.swing.ImageIcon(getClass().getResource("/resources/Icons/wrench-simple.png")), registerTabPanel1, "click to record new tool"); // NOI18N

        borrowTabPanel1.setBackground(new java.awt.Color(249, 251, 253));

        jLabel7.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("Select tool from the available listed tools below, fill its state and submit");

        borrowTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tool S/N", "Name", "Available Quantity", "Description"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        borrowTable.setGridColor(new java.awt.Color(255, 0, 153));
        borrowTable.setSelectionBackground(new java.awt.Color(0, 153, 255));
        borrowTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        borrowTable.setShowGrid(true);
        jScrollPane2.setViewportView(borrowTable);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setLabelFor(staffIdBorrowTF);
        jLabel8.setText("Staff National ID");

        staffIdBorrowTF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        staffIdBorrowTF.setToolTipText("text\tborrowing staff national ID");
        staffIdBorrowTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numericKeyTypedHandler(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setLabelFor(goodQtyBorrowTF);
        jLabel9.setText("Good Quantity");
        jLabel9.setToolTipText("");

        goodQtyBorrowTF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        goodQtyBorrowTF.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        goodQtyBorrowTF.setToolTipText("tool amount borrowed that are good");
        goodQtyBorrowTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numericKeyTypedHandler(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setLabelFor(damageQtyBorrowTF);
        jLabel10.setText("Damaged Quantity");

        damageQtyBorrowTF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        damageQtyBorrowTF.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        damageQtyBorrowTF.setToolTipText("tool amount borrowed but damaged");
        damageQtyBorrowTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numericKeyTypedHandler(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setLabelFor(durationBorrowTF);
        jLabel11.setText("Duration (days)");

        durationBorrowTF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        durationBorrowTF.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        durationBorrowTF.setToolTipText("duration of tool borrow");
        durationBorrowTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numericKeyTypedHandler(evt);
            }
        });

        borrowResetButton.setBackground(new java.awt.Color(51, 204, 255));
        borrowResetButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        borrowResetButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Icons/refresh(1).png"))); // NOI18N
        borrowResetButton.setText("Reset");
        borrowResetButton.setToolTipText("click to reset all fields");
        borrowResetButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        borrowResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrowResetButtonHandler(evt);
            }
        });

        borrowSubmitButton.setBackground(new java.awt.Color(51, 204, 255));
        borrowSubmitButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        borrowSubmitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Icons/folder-download(1).png"))); // NOI18N
        borrowSubmitButton.setText("Submit");
        borrowSubmitButton.setToolTipText("click to submit tool borrow");
        borrowSubmitButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        borrowSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrowSubmitButtonHandler(evt);
            }
        });

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Images/image1.jpeg"))); // NOI18N

        javax.swing.GroupLayout borrowTabPanel1Layout = new javax.swing.GroupLayout(borrowTabPanel1);
        borrowTabPanel1.setLayout(borrowTabPanel1Layout);
        borrowTabPanel1Layout.setHorizontalGroup(
            borrowTabPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(borrowTabPanel1Layout.createSequentialGroup()
                .addGroup(borrowTabPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(borrowTabPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(borrowTabPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
                            .addComponent(jScrollPane2))
                        .addGap(48, 48, 48)
                        .addGroup(borrowTabPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(borrowTabPanel1Layout.createSequentialGroup()
                                .addGroup(borrowTabPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(borrowTabPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(staffIdBorrowTF, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(goodQtyBorrowTF, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(damageQtyBorrowTF, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(durationBorrowTF, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(borrowTabPanel1Layout.createSequentialGroup()
                                .addComponent(borrowResetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(borrowSubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(borrowTabPanel1Layout.createSequentialGroup()
                        .addGap(342, 342, 342)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        borrowTabPanel1Layout.setVerticalGroup(
            borrowTabPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(borrowTabPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(borrowTabPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(borrowTabPanel1Layout.createSequentialGroup()
                        .addGroup(borrowTabPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(borrowTabPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(borrowTabPanel1Layout.createSequentialGroup()
                                .addComponent(staffIdBorrowTF, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(goodQtyBorrowTF, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(damageQtyBorrowTF, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(durationBorrowTF, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(74, 74, 74)
                        .addGroup(borrowTabPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(borrowResetButton, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                            .addComponent(borrowSubmitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        toolsTabbedPane1.addTab("Tool Borrow  ", new javax.swing.ImageIcon(getClass().getResource("/resources/Icons/mobile.png")), borrowTabPanel1, "click to record a borrow"); // NOI18N

        returnTabPanel1.setBackground(new java.awt.Color(249, 251, 253));

        jLabel1.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Select tool from table, fill description then submit... if unavailable, search");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setLabelFor(staffIdSearchTF);
        jLabel2.setText("Staff National ID");

        staffIdSearchTF.setToolTipText("returning staff national ID");
        staffIdSearchTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numericKeyTypedHandler(evt);
            }
        });

        searchBorrowButton.setBackground(new java.awt.Color(204, 204, 204));
        searchBorrowButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        searchBorrowButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Icons/search.png"))); // NOI18N
        searchBorrowButton.setText("Search");
        searchBorrowButton.setToolTipText("click to search tools borrowed previously by this staff");
        searchBorrowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBorrowButtonHandler(evt);
            }
        });

        returnTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tool S/N", "Name", "Good Qty", "Damaged Qty", "Duration", "First Name", "Mid Name", "Timestamp"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        returnTable.setGridColor(new java.awt.Color(255, 51, 0));
        returnTable.setSelectionBackground(new java.awt.Color(255, 0, 153));
        returnTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        returnTable.setShowGrid(true);
        jScrollPane1.setViewportView(returnTable);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setLabelFor(goodQtyReturnTF);
        jLabel3.setText("Good Quantity");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        submitGoodButton.setBackground(new java.awt.Color(51, 204, 255));
        submitGoodButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        submitGoodButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Icons/folder-download(1).png"))); // NOI18N
        submitGoodButton.setText("Submit");
        submitGoodButton.setToolTipText("click to submit tool return");
        submitGoodButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        submitGoodButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitGoodButtonHandler(evt);
            }
        });

        resetGoodButton.setBackground(new java.awt.Color(51, 204, 255));
        resetGoodButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        resetGoodButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Icons/refresh(1).png"))); // NOI18N
        resetGoodButton.setText("Reset");
        resetGoodButton.setToolTipText("click to reset all fields");
        resetGoodButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        resetGoodButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetGoodButtonHandler(evt);
            }
        });

        damageReturnPanel.setBackground(new java.awt.Color(249, 251, 253));
        damageReturnPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Submit Tool Damage", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Monospaced", 1, 12), new java.awt.Color(255, 0, 0))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setLabelFor(damageSnTF);
        jLabel4.setText("Tool S/N");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setLabelFor(damageQtyReturnTF);
        jLabel5.setText("Damaged Quantity");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setLabelFor(damageUnderTF);
        jLabel6.setText("Damaged Under (ID)");

        damageSnTF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        damageSnTF.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        damageSnTF.setToolTipText("get tool S/N from table above");
        damageSnTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numericKeyTypedHandler(evt);
            }
        });

        damageQtyReturnTF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        damageQtyReturnTF.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        damageQtyReturnTF.setToolTipText("input number of damaged tools");
        damageQtyReturnTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numericKeyTypedHandler(evt);
            }
        });

        damageUnderTF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        damageUnderTF.setToolTipText("input ID number of culprit");
        damageUnderTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numericKeyTypedHandler(evt);
            }
        });

        submitDamageButton.setBackground(new java.awt.Color(204, 255, 0));
        submitDamageButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        submitDamageButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Icons/folder-download(1).png"))); // NOI18N
        submitDamageButton.setText("Submit");
        submitDamageButton.setToolTipText("click to submit damage record");
        submitDamageButton.setEnabled(false);
        submitDamageButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        submitDamageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitDamageButtonHandler(evt);
            }
        });

        clearDamageButton.setBackground(new java.awt.Color(204, 255, 0));
        clearDamageButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        clearDamageButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Icons/delete_1.png"))); // NOI18N
        clearDamageButton.setText("Clear");
        clearDamageButton.setToolTipText("click to clear fields");
        clearDamageButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        clearDamageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearDamageButtonHandler(evt);
            }
        });

        javax.swing.GroupLayout damageReturnPanelLayout = new javax.swing.GroupLayout(damageReturnPanel);
        damageReturnPanel.setLayout(damageReturnPanelLayout);
        damageReturnPanelLayout.setHorizontalGroup(
            damageReturnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(damageReturnPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(damageReturnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(damageReturnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(damageSnTF, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                    .addComponent(damageQtyReturnTF)
                    .addComponent(damageUnderTF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(damageReturnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(submitDamageButton, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                    .addComponent(clearDamageButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        damageReturnPanelLayout.setVerticalGroup(
            damageReturnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(damageReturnPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(damageReturnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(damageSnTF, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(damageReturnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(damageQtyReturnTF)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(clearDamageButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(damageReturnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(submitDamageButton, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(damageUnderTF))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        LostReturnPanel.setBackground(new java.awt.Color(249, 251, 253));
        LostReturnPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Submit Tool Loss", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Monospaced", 1, 12), new java.awt.Color(255, 0, 51))); // NOI18N

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel13.setLabelFor(lostSnTF);
        jLabel13.setText("Tool S/N");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel14.setLabelFor(lostQtyReturnTF);
        jLabel14.setText("Lost Quantity");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel15.setLabelFor(lostUnderTF);
        jLabel15.setText("Lost Under (ID)");

        lostSnTF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lostSnTF.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        lostSnTF.setToolTipText("get tool S/N from table above");
        lostSnTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numericKeyTypedHandler(evt);
            }
        });

        lostQtyReturnTF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lostQtyReturnTF.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        lostQtyReturnTF.setToolTipText("input number of lost tools");
        lostQtyReturnTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numericKeyTypedHandler(evt);
            }
        });

        lostUnderTF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lostUnderTF.setToolTipText("input ID of tool loss culprit");
        lostUnderTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numericKeyTypedHandler(evt);
            }
        });

        submitLostButton.setBackground(new java.awt.Color(204, 153, 255));
        submitLostButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        submitLostButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Icons/folder-download(1).png"))); // NOI18N
        submitLostButton.setText("Submit");
        submitLostButton.setToolTipText("click to submit lost record");
        submitLostButton.setEnabled(false);
        submitLostButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        submitLostButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitLostButtonHandler(evt);
            }
        });

        clearLostButton.setBackground(new java.awt.Color(204, 153, 255));
        clearLostButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        clearLostButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Icons/delete_1.png"))); // NOI18N
        clearLostButton.setText("Clear");
        clearLostButton.setToolTipText("click to clear fields");
        clearLostButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        clearLostButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearLostButtonHandler(evt);
            }
        });

        javax.swing.GroupLayout LostReturnPanelLayout = new javax.swing.GroupLayout(LostReturnPanel);
        LostReturnPanel.setLayout(LostReturnPanelLayout);
        LostReturnPanelLayout.setHorizontalGroup(
            LostReturnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LostReturnPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LostReturnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(LostReturnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lostSnTF, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                    .addComponent(lostQtyReturnTF)
                    .addComponent(lostUnderTF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(LostReturnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(submitLostButton, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                    .addComponent(clearLostButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        LostReturnPanelLayout.setVerticalGroup(
            LostReturnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LostReturnPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(LostReturnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lostSnTF, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(LostReturnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(clearLostButton, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(lostQtyReturnTF)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(LostReturnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(submitLostButton, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lostUnderTF, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        goodQtyReturnTF.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        goodQtyReturnTF.setToolTipText("input number of tools in good measure");
        goodQtyReturnTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numericKeyTypedHandler(evt);
            }
        });

        javax.swing.GroupLayout returnTabPanel1Layout = new javax.swing.GroupLayout(returnTabPanel1);
        returnTabPanel1.setLayout(returnTabPanel1Layout);
        returnTabPanel1Layout.setHorizontalGroup(
            returnTabPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(returnTabPanel1Layout.createSequentialGroup()
                .addGroup(returnTabPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(returnTabPanel1Layout.createSequentialGroup()
                        .addGroup(returnTabPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(returnTabPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(returnTabPanel1Layout.createSequentialGroup()
                                .addGap(194, 194, 194)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(staffIdSearchTF, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(searchBorrowButton, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 441, Short.MAX_VALUE))
                    .addGroup(returnTabPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(returnTabPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(returnTabPanel1Layout.createSequentialGroup()
                                .addGap(542, 542, 542)
                                .addComponent(submitGoodButton, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(109, 109, 109)
                                .addComponent(resetGoodButton, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, returnTabPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(returnTabPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(returnTabPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(goodQtyReturnTF, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(returnTabPanel1Layout.createSequentialGroup()
                        .addComponent(damageReturnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(LostReturnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42))
        );
        returnTabPanel1Layout.setVerticalGroup(
            returnTabPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(returnTabPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(returnTabPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(staffIdSearchTF)
                    .addComponent(searchBorrowButton, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(returnTabPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resetGoodButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(returnTabPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(submitGoodButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(returnTabPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(goodQtyReturnTF, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(returnTabPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(damageReturnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LostReturnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54))
        );

        toolsTabbedPane1.addTab("Tool Return  ", new javax.swing.ImageIcon(getClass().getResource("/resources/Icons/people-poll(1).png")), returnTabPanel1, "click to record a return"); // NOI18N

        javax.swing.GroupLayout toolsMainPanel1Layout = new javax.swing.GroupLayout(toolsMainPanel1);
        toolsMainPanel1.setLayout(toolsMainPanel1Layout);
        toolsMainPanel1Layout.setHorizontalGroup(
            toolsMainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toolsMainPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(toolsTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        toolsMainPanel1Layout.setVerticalGroup(
            toolsMainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toolsMainPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(toolsTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toolsMainPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toolsMainPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void numericKeyTypedHandler(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numericKeyTypedHandler
        // get typed character
        char testChar = evt.getKeyChar();
        // if not numeric/digit reject character        
        if(!(Character.isDigit(testChar)))  {
            evt.consume();
        }
    }//GEN-LAST:event_numericKeyTypedHandler

    private void toolClearButtonHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toolClearButtonHandler
        // clear all fields
        toolNameTF.setText("");
        toolBuyQtyTF.setText("0");
        toolBuyDateTF.setText("YYYY-MM-DD");
        toolBuyPriceFormattedTF.setText("");
        toolDescriptionTextArea.setText("");
        toolSaveButton.setEnabled(true);
    }//GEN-LAST:event_toolClearButtonHandler

    private void toolSaveButtonHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toolSaveButtonHandler
        // confirm text fields not empty
        if(toolNameTF.getText().isBlank() || toolBuyQtyTF.getText().isBlank() || toolBuyDateTF.getText().isBlank()) {
            // display error message
            JOptionPane.showMessageDialog( null, "Please Fill All Fields!\nTool Description is optional!", "Add New Tool Error - Street Sparkle", JOptionPane.WARNING_MESSAGE );
        } else {
            try {                
                String toolSize = toolSizeComboBox.getSelectedItem().toString();
                int buyQty = Integer.parseInt(toolBuyQtyTF.getText());
                float buyPrice = Float.parseFloat(toolBuyPriceFormattedTF.getValue().toString());
                // validate purchased date input
                if(Authenticator.validateDate(toolBuyDateTF.getText()) == false) {
                    // display error message
                    JOptionPane.showMessageDialog( null, "Please input valid Date!\neg.2023-05-03", "Add New Tool Error - Street Sparkle", JOptionPane.WARNING_MESSAGE );
                }
                // check buy qty and price greater than zero
                else if(buyQty <= 0 || buyPrice <= 0.0) {
                    // display error message
                    JOptionPane.showMessageDialog( null, "Buy Quantity and Buy Price values should be greater than zero!", "Add New Tool Error - Street Sparkle", JOptionPane.WARNING_MESSAGE );
                }
                // record new tool details to database
                else {                    
                    database.addTool(toolNameTF.getText(), toolSize, buyPrice, toolBuyDateTF.getText(), buyQty, toolSaveButton);
                    database.updateToolDescription(toolDescriptionTextArea.getText(), toolNameTF.getText());
                }
                
            } catch(DateTimeParseException e) {
                // display error message
                JOptionPane.showMessageDialog( null, "Please input valid Date!", "Add New Tool Error - Street Sparkle", JOptionPane.WARNING_MESSAGE );
            }     
        } // end outer else
    }//GEN-LAST:event_toolSaveButtonHandler

    private void mouseClickedHandler(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseClickedHandler
        // clear table and list data
        aTool.getToolList1().clear(); // clear list objects
        aTool.getToolList2().clear(); // clear list objects
        // clear tools table data 
        DefaultTableModel model = ( DefaultTableModel ) borrowTable.getModel();
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged(); // notifies the JTable that the model has changed
        // clear tool return table data 
        DefaultTableModel model1 = ( DefaultTableModel ) returnTable.getModel();
        model1.getDataVector().removeAllElements();
        model1.fireTableDataChanged(); // notifies the JTable that the model has changed
        // load data into tools table
        aTool.fetchToolDetails(borrowTable);
        // load data into tool return table
        aTool.fetchToolBorrows(returnTable);
    }//GEN-LAST:event_mouseClickedHandler

    private void borrowResetButtonHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrowResetButtonHandler
        // clear all fields 
        staffIdBorrowTF.setText("");
        goodQtyBorrowTF.setText("");
        damageQtyBorrowTF.setText("");
        durationBorrowTF.setText("");
        borrowSubmitButton.setEnabled(true);
        // clear table and list data
        aTool.getToolList1().clear(); // clear list objects
        // clear tools table data 
        DefaultTableModel model = ( DefaultTableModel ) borrowTable.getModel();
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged(); // notifies the JTable that the model has changed
    }//GEN-LAST:event_borrowResetButtonHandler

    private void borrowSubmitButtonHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrowSubmitButtonHandler
        // confirm text fields not empty
        if(staffIdBorrowTF.getText().isBlank() || goodQtyBorrowTF.getText().isBlank() || damageQtyBorrowTF.getText().isBlank() || durationBorrowTF.getText().isBlank()) {
            // display error message
            JOptionPane.showMessageDialog( null, "Please Fill All Fields!", "Add Tool Borrow Error - Street Sparkle", JOptionPane.WARNING_MESSAGE );
        } else {
            int staffId = Integer.parseInt(staffIdBorrowTF.getText());
            int goodQty = Integer.parseInt(goodQtyBorrowTF.getText());
            int damagedQty = Integer.parseInt(damageQtyBorrowTF.getText());
            int duration = Integer.parseInt(durationBorrowTF.getText());
            // ensure duration greater than zero
            if(duration <= 0) {
                // display error message
                JOptionPane.showMessageDialog( null, "Please ensure duration greater than zero!", "Add Tool Borrow Error - Street Sparkle", JOptionPane.WARNING_MESSAGE );
            }
            // validate input id value
            else if(Authenticator.validateID(staffIdBorrowTF.getText()) == false) {
                // display error message
                JOptionPane.showMessageDialog( null, "Please input a valid ID number (8 digits)!", "Add Tool Borrow Error - Street Sparkle", JOptionPane.WARNING_MESSAGE );
            }
            // confirm selection from table
            else if(borrowTable.getSelectionModel().isSelectionEmpty() == true) {
                // displaying of NULL items selected error message */
                JOptionPane.showMessageDialog( null, "Select a Tool from Table!","Tool Borrow Error- Street Sparkle", JOptionPane.WARNING_MESSAGE ); 
            }
            // record borrow into database
            else {
                aTool.addToolBorrow(staffId, goodQty, damagedQty, duration, borrowTable, borrowSubmitButton);
            }
        }
    }//GEN-LAST:event_borrowSubmitButtonHandler

    private void componentHiddenHandler(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_componentHiddenHandler
        // clear table and list data
        aTool.getToolList1().clear(); // clear list objects
         aTool.getToolList2().clear(); // clear list objects
        // clear supervisor table data 
        DefaultTableModel model1 = ( DefaultTableModel ) borrowTable.getModel();
        model1.getDataVector().removeAllElements();
        model1.fireTableDataChanged(); // notifies the JTable that the model has changed
        // clear projects table data 
        DefaultTableModel model = ( DefaultTableModel ) returnTable.getModel();
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged(); // notifies the JTable that the model has changed
        // close database connection
        //database.closeDB();
    }//GEN-LAST:event_componentHiddenHandler

    private void resetGoodButtonHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetGoodButtonHandler
        // clear textfields and table data
        staffIdSearchTF.setText("");
        goodQtyReturnTF.setText("");
        submitGoodButton.setEnabled(true);
        submitDamageButton.setEnabled(false);
        submitLostButton.setEnabled(false);
        returnTable.clearSelection();
    }//GEN-LAST:event_resetGoodButtonHandler

    private void submitGoodButtonHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitGoodButtonHandler
        // confirm text fields not empty
        if(goodQtyReturnTF.getText().isBlank() ) {
            // display error message
            JOptionPane.showMessageDialog( null, "Please Fill Good quantity field!", "Add Tool Return Error - Street Sparkle", JOptionPane.WARNING_MESSAGE );
        }
        // confirm selection from table
        else if(returnTable.getSelectionModel().isSelectionEmpty() == true) {
            // displaying of NULL items selected error message */
            JOptionPane.showMessageDialog( null, "Select a Tool from Table!","Tool Return Error- Street Sparkle", JOptionPane.WARNING_MESSAGE ); 
        }
        // record return into database
        else {
            aTool.addToolReturn(Integer.parseInt(goodQtyReturnTF.getText()), returnTable, submitGoodButton);
            submitDamageButton.setEnabled(true); // enable to submit tool damage if any
            submitLostButton.setEnabled(true); // enable to submit tool lost if any
        }        
    }//GEN-LAST:event_submitGoodButtonHandler

    private void searchBorrowButtonHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBorrowButtonHandler
        // confirm text fields not empty
        if(staffIdSearchTF.getText().isBlank() ) {
            // display error message
            JOptionPane.showMessageDialog( null, "Please Fill Staff national id field!", "Add Tool Return Error - Street Sparkle", JOptionPane.WARNING_MESSAGE );
        }
        // validate input id value
        else if(Authenticator.validateID(staffIdSearchTF.getText()) == false) {
            // display error message
            JOptionPane.showMessageDialog( null, "Please input a valid ID number (8 digits)!", "Add Tool Return Error - Street Sparkle", JOptionPane.WARNING_MESSAGE );
        } 
        else {
            // clear tools table data 
            DefaultTableModel model = ( DefaultTableModel ) returnTable.getModel();
            model.getDataVector().removeAllElements();
            model.fireTableDataChanged(); // notifies the JTable that the model has changed
            aTool.getToolList2().clear(); // clear list objects
            // load data into table
            aTool.fetchStaffToolBorrow(Integer.parseInt(staffIdSearchTF.getText()), returnTable);
        }
    }//GEN-LAST:event_searchBorrowButtonHandler

    private void clearDamageButtonHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearDamageButtonHandler
        // clear all fields
        damageSnTF.setText("");
        damageQtyReturnTF.setText("");
        damageUnderTF.setText("");
        submitDamageButton.setEnabled(false);
    }//GEN-LAST:event_clearDamageButtonHandler

    private void submitDamageButtonHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitDamageButtonHandler
        // confirm text fields not empty
        if(damageSnTF.getText().isBlank() || damageQtyReturnTF.getText().isBlank() || damageUnderTF.getText().isBlank()) {
            // display error message
            JOptionPane.showMessageDialog( null, "Please Fill All fields!", "Tool Damage Error - Street Sparkle", JOptionPane.WARNING_MESSAGE );
        }
        // confirm damage qty greater than zero
        else if(Integer.parseInt(damageQtyReturnTF.getText()) <= 0) {
            // display error message
            JOptionPane.showMessageDialog( null, "Damaged quantity should be greater than zero!", "Tool Damage Error - Street Sparkle", JOptionPane.WARNING_MESSAGE );
        }
        // validate input id value
        else if(Authenticator.validateID(damageUnderTF.getText()) == false) {
            // display error message
            JOptionPane.showMessageDialog( null, "Please input a valid ID number (8 digits)!", "Tool Damage Error - Street Sparkle", JOptionPane.WARNING_MESSAGE );
        }
        // record into database
        else {
            aTool.updateToolDamage(Integer.parseInt(damageSnTF.getText()), Integer.parseInt(damageQtyReturnTF.getText()), 
                    damageUnderTF.getText(), submitDamageButton);
        }    
    }//GEN-LAST:event_submitDamageButtonHandler

    private void clearLostButtonHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearLostButtonHandler
        // clear all fields
        lostSnTF.setText("");
        lostQtyReturnTF.setText("");
        lostUnderTF.setText("");
        submitLostButton.setEnabled(false);
    }//GEN-LAST:event_clearLostButtonHandler

    private void submitLostButtonHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitLostButtonHandler
        // confirm text fields not empty
        if(lostSnTF.getText().isBlank() || lostQtyReturnTF.getText().isBlank() || lostUnderTF.getText().isBlank()) {
            // display error message
            JOptionPane.showMessageDialog( null, "Please Fill All fields!", "Tool Lost  Error - Street Sparkle", JOptionPane.WARNING_MESSAGE );
        }
        // confirm damage qty greater than zero
        else if(Integer.parseInt(lostQtyReturnTF.getText()) <= 0) {
            // display error message
            JOptionPane.showMessageDialog( null, "Damaged quantity should be greater than zero!", "Tool Lost Error - Street Sparkle", JOptionPane.WARNING_MESSAGE );
        }
        // validate input id value
        else if(Authenticator.validateID(lostUnderTF.getText()) == false) {
            // display error message
            JOptionPane.showMessageDialog( null, "Please input a valid ID number (8 digits)!", "Tool Lost Error - Street Sparkle", JOptionPane.WARNING_MESSAGE );
        }
        // record into database
        else {
            aTool.updateToolLost(Integer.parseInt(lostSnTF.getText()), Integer.parseInt(lostQtyReturnTF.getText()), 
                    lostUnderTF.getText(), submitLostButton);
        } 
    }//GEN-LAST:event_submitLostButtonHandler


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LostReturnPanel;
    private javax.swing.JButton borrowResetButton;
    private javax.swing.JButton borrowSubmitButton;
    private javax.swing.JPanel borrowTabPanel1;
    private javax.swing.JTable borrowTable;
    private javax.swing.JButton clearDamageButton;
    private javax.swing.JButton clearLostButton;
    private javax.swing.JTextField damageQtyBorrowTF;
    private javax.swing.JTextField damageQtyReturnTF;
    private javax.swing.JPanel damageReturnPanel;
    private javax.swing.JTextField damageSnTF;
    private javax.swing.JTextField damageUnderTF;
    private javax.swing.JTextField durationBorrowTF;
    private javax.swing.JTextField goodQtyBorrowTF;
    private javax.swing.JTextField goodQtyReturnTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField lostQtyReturnTF;
    private javax.swing.JTextField lostSnTF;
    private javax.swing.JTextField lostUnderTF;
    private javax.swing.JPanel registerTabPanel1;
    private javax.swing.JButton resetGoodButton;
    private javax.swing.JPanel returnTabPanel1;
    private javax.swing.JTable returnTable;
    private javax.swing.JButton searchBorrowButton;
    private javax.swing.JTextField staffIdBorrowTF;
    private javax.swing.JTextField staffIdSearchTF;
    private javax.swing.JButton submitDamageButton;
    private javax.swing.JButton submitGoodButton;
    private javax.swing.JButton submitLostButton;
    private javax.swing.JTextField toolBuyDateTF;
    private javax.swing.JFormattedTextField toolBuyPriceFormattedTF;
    private javax.swing.JTextField toolBuyQtyTF;
    private javax.swing.JButton toolClearButton;
    private javax.swing.JTextArea toolDescriptionTextArea;
    private javax.swing.JTextField toolNameTF;
    private javax.swing.JButton toolSaveButton;
    private javax.swing.JComboBox<String> toolSizeComboBox;
    private javax.swing.JPanel toolsMainPanel1;
    private javax.swing.JTabbedPane toolsTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
