/*
 * @author John Felix 
 *
 */
package myDuka;

public class AuthenticationUI extends javax.swing.JFrame {

    /**
     * Creates new form AuthenticationUI
     */
    public Authenticator authenticator; // class Authenticator object declaration to handle all authentication
    
    public AuthenticationUI() {
        authenticator = new Authenticator();
        initComponents();       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        authenticationPanel = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        headerL = new javax.swing.JLabel();
        mottoL = new javax.swing.JLabel();
        usernameJL = new javax.swing.JLabel();
        usernameTF = new javax.swing.JTextField();
        usernameL = new javax.swing.JLabel();
        passwordJL = new javax.swing.JLabel();
        passwordPF = new javax.swing.JPasswordField();
        passwordL = new javax.swing.JLabel();
        logginJB = new javax.swing.JButton();
        clearJB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Authentication - MyDuka");
        setPreferredSize(new java.awt.Dimension(650, 470));
        setResizable(false);

        authenticationPanel.setBackground(new java.awt.Color(255, 224, 255));

        headerPanel.setBackground(new java.awt.Color(255, 255, 153));

        headerL.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        headerL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerL.setText("MyDuka Retail App");

        mottoL.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        mottoL.setForeground(new java.awt.Color(0, 153, 51));
        mottoL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mottoL.setText("For all your Retail Software needs!");

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(headerL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mottoL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headerL, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mottoL, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        usernameJL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        usernameJL.setLabelFor(usernameTF);
        usernameJL.setText("Username");

        usernameTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        usernameL.setForeground(new java.awt.Color(255, 0, 0));
        usernameL.setLabelFor(usernameTF);

        passwordJL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        passwordJL.setLabelFor(passwordPF);
        passwordJL.setText("Password");

        passwordPF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        passwordL.setForeground(new java.awt.Color(255, 0, 0));
        passwordL.setLabelFor(passwordPF);

        logginJB.setBackground(new java.awt.Color(153, 255, 51));
        logginJB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        logginJB.setText("Login");
        logginJB.setToolTipText("click to login");
        logginJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginHandler(evt);
            }
        });

        clearJB.setBackground(new java.awt.Color(153, 255, 51));
        clearJB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clearJB.setText("Clear");
        clearJB.setToolTipText("click to reset fields");
        clearJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearHandler(evt);
            }
        });

        javax.swing.GroupLayout authenticationPanelLayout = new javax.swing.GroupLayout(authenticationPanel);
        authenticationPanel.setLayout(authenticationPanelLayout);
        authenticationPanelLayout.setHorizontalGroup(
            authenticationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(authenticationPanelLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(authenticationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(usernameJL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(usernameTF)
                    .addComponent(usernameL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(passwordJL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(passwordPF)
                    .addComponent(passwordL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(authenticationPanelLayout.createSequentialGroup()
                        .addComponent(logginJB, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                        .addComponent(clearJB, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        authenticationPanelLayout.setVerticalGroup(
            authenticationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(authenticationPanelLayout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(usernameJL, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usernameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usernameL, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordJL, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordPF, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordL, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(authenticationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(logginJB, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(clearJB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 60, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(authenticationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(authenticationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleParent(this);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void clearHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearHandler
        // clear text in fields
        usernameTF.setText("");
        passwordPF.setText("");
        usernameL.setText("");
        passwordL.setText("");
        
    }//GEN-LAST:event_clearHandler

    private void loginHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginHandler
        // validating of input
        if(usernameTF.getText().isBlank() && passwordPF.getText().isBlank()) {
            // display required field
            usernameL.setVisible(true);
            usernameL.setText("Required field");
            passwordL.setVisible(true);
            passwordL.setText("Required field");

        } else if(usernameTF.getText().isBlank()) {
            // display required field
            usernameL.setVisible(true);
            usernameL.setText("Required field");
            passwordL.setText("");

        } else if(passwordPF.getText().isBlank()) {
            // display required field
            passwordL.setVisible(true);
            passwordL.setText("Required field");
            usernameL.setText("");
            
        } else {
            // clear labels
            usernameL.setText("");
            passwordL.setText("");
            // authenticate user and load appropriate interface           
            authenticator.loadUI(usernameTF.getText(), passwordPF.getText(), passwordL, usernameTF, passwordPF);
            
        }         
    }//GEN-LAST:event_loginHandler

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AuthenticationUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AuthenticationUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AuthenticationUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AuthenticationUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AuthenticationUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel authenticationPanel;
    private javax.swing.JButton clearJB;
    private javax.swing.JLabel headerL;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JButton logginJB;
    private javax.swing.JLabel mottoL;
    private javax.swing.JLabel passwordJL;
    private javax.swing.JLabel passwordL;
    private javax.swing.JPasswordField passwordPF;
    private javax.swing.JLabel usernameJL;
    private javax.swing.JLabel usernameL;
    private javax.swing.JTextField usernameTF;
    // End of variables declaration//GEN-END:variables
}
