/*
 * @author John Felix 
 *
 */
package myDuka;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class StaffUI extends javax.swing.JFrame {

    /**
     * Creates new form StaffUI
     */
    public Database database; // class Database object declaration to handle database services
    public Customer custom; // class Customer object to handle making of sales
    public Detailer pharmaDetails; // class Detailer object to handle setting/details
    public float totalAmount = 0.00f; // stores intermediate total amount
    
    public StaffUI() {
        database = new Database();
        custom = new Customer();
        pharmaDetails = new Detailer();
        // call class Detailer functions to set interface details
        pharmaDetails.fetchCompanyDetails();
        pharmaDetails.fetchMonetaryDetails();
        // general interface components initialization
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPanel = new javax.swing.JPanel();
        titleL = new javax.swing.JLabel();
        footerPanel = new javax.swing.JPanel();
        footerL = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        salesTabPanel = new javax.swing.JPanel();
        itemNameL = new javax.swing.JLabel();
        itemNameTF = new javax.swing.JTextField();
        buyQuantityTF = new javax.swing.JTextField();
        buyQuantityL = new javax.swing.JLabel();
        addItemJB = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        salesTable = new javax.swing.JTable();
        totalL = new javax.swing.JLabel();
        totalTF = new javax.swing.JTextField();
        payAmountL = new javax.swing.JLabel();
        balanceL = new javax.swing.JLabel();
        balanceTF = new javax.swing.JTextField();
        purchaseJB = new javax.swing.JButton();
        clearSaleJB = new javax.swing.JButton();
        measurementL = new javax.swing.JLabel();
        measurementCB = new javax.swing.JComboBox<>();
        measurementFormattedTF = new javax.swing.JFormattedTextField();
        paymentMethodPanel = new javax.swing.JPanel();
        mobilePayL = new javax.swing.JLabel();
        bankPayL = new javax.swing.JLabel();
        cardPayL = new javax.swing.JLabel();
        mobilePayDataL = new javax.swing.JLabel();
        bankPayDataL = new javax.swing.JLabel();
        cardPayDataL = new javax.swing.JLabel();
        payAmountFormattedTF = new javax.swing.JFormattedTextField();
        saleInstructionL = new javax.swing.JLabel();
        resetJB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sales - MyDuka");
        setBackground(new java.awt.Color(255, 255, 255));
        setExtendedState(6);
        setMinimumSize(new java.awt.Dimension(1266, 700));
        setPreferredSize(new java.awt.Dimension(1366, 749));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                windowClosingHandler(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                windowOpenedHandler(evt);
            }
        });

        headerPanel.setBackground(new java.awt.Color(255, 255, 153));

        titleL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        titleL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleL.setLabelFor(headerPanel);
        titleL.setText("enterprise title here..");
        titleL.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(titleL, javax.swing.GroupLayout.PREFERRED_SIZE, 1050, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        footerPanel.setBackground(new java.awt.Color(255, 255, 153));

        footerL.setFont(new java.awt.Font("Vivaldi", 3, 18)); // NOI18N
        footerL.setForeground(new java.awt.Color(255, 0, 0));
        footerL.setLabelFor(footerPanel);
        footerL.setText("motto/mission statement here...");

        javax.swing.GroupLayout footerPanelLayout = new javax.swing.GroupLayout(footerPanel);
        footerPanel.setLayout(footerPanelLayout);
        footerPanelLayout.setHorizontalGroup(
            footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(footerL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        footerPanelLayout.setVerticalGroup(
            footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, footerPanelLayout.createSequentialGroup()
                .addComponent(footerL, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.setBackground(new java.awt.Color(249, 251, 253));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 133, 24), new java.awt.Color(255, 133, 24), java.awt.Color.orange, java.awt.Color.orange));
        jTabbedPane1.setToolTipText("");

        salesTabPanel.setBackground(new java.awt.Color(249, 251, 253));
        salesTabPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 55, 0)));

        itemNameL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        itemNameL.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        itemNameL.setLabelFor(itemNameTF);
        itemNameL.setText("Item Name");

        itemNameTF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        buyQuantityTF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        buyQuantityTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numericKeyTypedHandler(evt);
            }
        });

        buyQuantityL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buyQuantityL.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        buyQuantityL.setLabelFor(buyQuantityTF);
        buyQuantityL.setText("Buy Quantity");

        addItemJB.setBackground(new java.awt.Color(178, 255, 255));
        addItemJB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        addItemJB.setText("Add Item");
        addItemJB.setToolTipText("add item to same customer");
        addItemJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addItemJBHandler(evt);
            }
        });

        salesTable.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        salesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Barcode", "Item Name", "Measurement", "Item Price", "Sale Quantity", "Sub-Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Integer.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        salesTable.setToolTipText("Items to purchase");
        salesTable.setGridColor(new java.awt.Color(255, 51, 0));
        salesTable.setRowSelectionAllowed(false);
        salesTable.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        salesTable.setShowGrid(true);
        jScrollPane1.setViewportView(salesTable);

        totalL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        totalL.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        totalL.setLabelFor(totalTF);
        totalL.setText("TOTAL PRICE");

        totalTF.setEditable(false);
        totalTF.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        totalTF.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        payAmountL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        payAmountL.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        payAmountL.setLabelFor(payAmountFormattedTF);
        payAmountL.setText("Payed Amount");

        balanceL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        balanceL.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        balanceL.setLabelFor(balanceTF);
        balanceL.setText("BALANCE");

        balanceTF.setEditable(false);
        balanceTF.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        balanceTF.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        purchaseJB.setBackground(new java.awt.Color(102, 255, 255));
        purchaseJB.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        purchaseJB.setText("Purchase Item");
        purchaseJB.setToolTipText("click to record purchase");
        purchaseJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchaseJBHandler(evt);
            }
        });

        clearSaleJB.setBackground(new java.awt.Color(102, 255, 255));
        clearSaleJB.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        clearSaleJB.setText("Clear");
        clearSaleJB.setToolTipText("click to reset all fields");
        clearSaleJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearSalesJBHandler(evt);
            }
        });

        measurementL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        measurementL.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        measurementL.setLabelFor(measurementFormattedTF);
        measurementL.setText("Measurement");

        measurementCB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        measurementCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "g", "Kg", "mg", "ml", "L", "m x m" }));
        measurementCB.setToolTipText("select drug measurement");

        measurementFormattedTF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        measurementFormattedTF.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        measurementFormattedTF.setToolTipText("input value and select measurement");
        measurementFormattedTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        paymentMethodPanel.setBackground(new java.awt.Color(249, 251, 253));
        paymentMethodPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Accepted Payment Methods", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        mobilePayL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mobilePayL.setLabelFor(mobilePayDataL);
        mobilePayL.setText("Mobile Payment:");

        bankPayL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bankPayL.setLabelFor(bankPayDataL);
        bankPayL.setText("Bank Payment:");

        cardPayL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cardPayL.setLabelFor(cardPayDataL);
        cardPayL.setText("Card Payment:");

        mobilePayDataL.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        mobilePayDataL.setForeground(new java.awt.Color(255, 102, 0));
        mobilePayDataL.setLabelFor(mobilePayL);

        bankPayDataL.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        bankPayDataL.setForeground(new java.awt.Color(255, 102, 0));
        bankPayDataL.setLabelFor(bankPayL);

        cardPayDataL.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cardPayDataL.setForeground(new java.awt.Color(255, 102, 0));
        cardPayDataL.setLabelFor(cardPayL);

        javax.swing.GroupLayout paymentMethodPanelLayout = new javax.swing.GroupLayout(paymentMethodPanel);
        paymentMethodPanel.setLayout(paymentMethodPanelLayout);
        paymentMethodPanelLayout.setHorizontalGroup(
            paymentMethodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paymentMethodPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paymentMethodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mobilePayL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bankPayL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cardPayL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paymentMethodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mobilePayDataL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bankPayDataL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cardPayDataL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        paymentMethodPanelLayout.setVerticalGroup(
            paymentMethodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paymentMethodPanelLayout.createSequentialGroup()
                .addGroup(paymentMethodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mobilePayL, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(mobilePayDataL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paymentMethodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bankPayL, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bankPayDataL, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paymentMethodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cardPayL, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardPayDataL, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 4, Short.MAX_VALUE))
        );

        payAmountFormattedTF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        payAmountFormattedTF.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        payAmountFormattedTF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        saleInstructionL.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        saleInstructionL.setForeground(new java.awt.Color(255, 153, 0));
        saleInstructionL.setText("Input the Item Details to Sell");

        resetJB.setBackground(new java.awt.Color(178, 255, 255));
        resetJB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        resetJB.setText("Reset");
        resetJB.setToolTipText("click to clear item details");
        resetJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetJBHandler(evt);
            }
        });

        javax.swing.GroupLayout salesTabPanelLayout = new javax.swing.GroupLayout(salesTabPanel);
        salesTabPanel.setLayout(salesTabPanelLayout);
        salesTabPanelLayout.setHorizontalGroup(
            salesTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salesTabPanelLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(salesTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(salesTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(salesTabPanelLayout.createSequentialGroup()
                            .addGroup(salesTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(balanceL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(payAmountL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(totalL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(salesTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(purchaseJB, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(salesTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(payAmountFormattedTF, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(totalTF, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(balanceTF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(salesTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(salesTabPanelLayout.createSequentialGroup()
                                    .addComponent(clearSaleJB, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(56, 56, 56))
                                .addComponent(paymentMethodPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(salesTabPanelLayout.createSequentialGroup()
                            .addGroup(salesTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(salesTabPanelLayout.createSequentialGroup()
                                    .addComponent(measurementL, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(measurementFormattedTF)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(measurementCB, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(salesTabPanelLayout.createSequentialGroup()
                                    .addComponent(itemNameL, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(itemNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(18, 18, 18)
                            .addComponent(buyQuantityL, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(salesTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(addItemJB, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                .addComponent(buyQuantityTF, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(resetJB, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(saleInstructionL, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(121, Short.MAX_VALUE))
        );
        salesTabPanelLayout.setVerticalGroup(
            salesTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salesTabPanelLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(saleInstructionL, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(salesTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, salesTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buyQuantityL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buyQuantityTF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(itemNameL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemNameTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(salesTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(measurementL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(salesTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(measurementFormattedTF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(measurementCB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(addItemJB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(resetJB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(salesTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(salesTabPanelLayout.createSequentialGroup()
                        .addGroup(salesTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(totalL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(totalTF, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(salesTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(payAmountL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(payAmountFormattedTF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(salesTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(balanceL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(balanceTF, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)))
                    .addComponent(paymentMethodPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(salesTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(purchaseJB, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(clearSaleJB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("SALES        ", null, salesTabPanel, "click to record sale");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jTabbedPane1)
                .addGap(5, 5, 5))
            .addComponent(footerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(footerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        headerPanel.getAccessibleContext().setAccessibleName("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void windowOpenedHandler(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_windowOpenedHandler
        // set window size to fullscreen when window is opened
        this.setExtendedState(StaffUI.MAXIMIZED_BOTH);
        // set enterprise title
        titleL.setText( Detailer.getCompanyTitle() );
        // set enterprise motto/vision
        footerL.setText( Detailer.getCompanyMotto() );
        /* set enterprise accepted payment options */
        mobilePayDataL.setText( Detailer.getMobilePay() ); 
        bankPayDataL.setText( Detailer.getBankPay() );
        cardPayDataL.setText( Detailer.getCardPay() );
    }//GEN-LAST:event_windowOpenedHandler

    private void numericKeyTypedHandler(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numericKeyTypedHandler
        // get typed character
        char testChar = evt.getKeyChar();
        // if not numeric/digit reject character        
        if(!(Character.isDigit(testChar)))  {
            evt.consume();
        }
    }//GEN-LAST:event_numericKeyTypedHandler

    private void windowClosingHandler(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_windowClosingHandler
        // close database connection then exit
        database.closeDatabase();
        System.exit(0);
    }//GEN-LAST:event_windowClosingHandler

    private void clearSalesJBHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearSalesJBHandler
        /* clear all fields in sales tab */
        itemNameTF.setText("");
        buyQuantityTF.setText("");
        measurementFormattedTF.setText("");
        measurementCB.setSelectedIndex(0);
        totalTF.setText("");
        payAmountFormattedTF.setText("");
        balanceTF.setText("");
        purchaseJB.setEnabled(true); // enable purchase button
        custom.getCustomerList().clear(); // clear list objects
        // clear table data 
        DefaultTableModel model = ( DefaultTableModel ) salesTable.getModel();
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged(); // notifies the JTable that the model has changed
    }//GEN-LAST:event_clearSalesJBHandler

    private void addItemJBHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addItemJBHandler
        // confirm text fields not blank
        if(itemNameTF.getText().isBlank() || buyQuantityTF.getText().isBlank() || measurementFormattedTF.getText().isBlank()) {
            // display error message
            JOptionPane.showMessageDialog( null, "Please Fill All Fields!", "Confirm Item Error- MyDuka", JOptionPane.WARNING_MESSAGE );
        } else if(Authenticator.validateBuyQuantity(buyQuantityTF.getText()) == false) {
            // display error message
            JOptionPane.showMessageDialog( null, "Input a valid quantity in the range 1-90!", "Confirm Item Error- MyDuka", JOptionPane.WARNING_MESSAGE );
        } else {
            String measureValue = measurementFormattedTF.getValue().toString();
            String measurement = measurementCB.getSelectedItem().toString();
            // confirm item if in database           
            this.totalAmount = custom.confirmItem( itemNameTF.getText(), 
                                                    measureValue,
                                                    measurement, 
                                                    Integer.parseInt(buyQuantityTF.getText()),
                                                    salesTable ); // end setText
            
            totalTF.setText(String.format("%,.2f", this.totalAmount)); 
        }  
    }//GEN-LAST:event_addItemJBHandler

    private void purchaseJBHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchaseJBHandler
        // confirm text fields not blank
        if( payAmountFormattedTF.getText().isBlank()) {
            // display error message
            JOptionPane.showMessageDialog( null, "Please fill Payed amount Field!", "Confirm Item Error- MyDuka", JOptionPane.WARNING_MESSAGE );
        } else {
            float payAmount = Float.parseFloat(payAmountFormattedTF.getValue().toString());
            // validate payed amount
            if(payAmount >= this.totalAmount) {
                // record purchase and calculate balance 
                balanceTF.setText(String.format("%,.2f", custom.purchaseItem( payAmount, 
                                                                              salesTable)) ); // end setText
                // disable button until clearing
                purchaseJB.setEnabled(false);
                
            } else {
                // display error message
                JOptionPane.showMessageDialog( null, "Payed amount cannot be less than total amount!", "Confirm Item Error- MyDuka", JOptionPane.WARNING_MESSAGE );
            }  
        }  
    }//GEN-LAST:event_purchaseJBHandler

    private void resetJBHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetJBHandler
        // clear these fields to record new item
        itemNameTF.setText("");
        buyQuantityTF.setText("");        
        measurementFormattedTF.setText("");        
    }//GEN-LAST:event_resetJBHandler

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StaffUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addItemJB;
    private javax.swing.JLabel balanceL;
    private javax.swing.JTextField balanceTF;
    private javax.swing.JLabel bankPayDataL;
    private javax.swing.JLabel bankPayL;
    private javax.swing.JLabel buyQuantityL;
    private javax.swing.JTextField buyQuantityTF;
    private javax.swing.JLabel cardPayDataL;
    private javax.swing.JLabel cardPayL;
    private javax.swing.JButton clearSaleJB;
    private javax.swing.JLabel footerL;
    private javax.swing.JPanel footerPanel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel itemNameL;
    private javax.swing.JTextField itemNameTF;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox<String> measurementCB;
    private javax.swing.JFormattedTextField measurementFormattedTF;
    private javax.swing.JLabel measurementL;
    private javax.swing.JLabel mobilePayDataL;
    private javax.swing.JLabel mobilePayL;
    private javax.swing.JFormattedTextField payAmountFormattedTF;
    private javax.swing.JLabel payAmountL;
    private javax.swing.JPanel paymentMethodPanel;
    private javax.swing.JButton purchaseJB;
    private javax.swing.JButton resetJB;
    private javax.swing.JLabel saleInstructionL;
    private javax.swing.JPanel salesTabPanel;
    private javax.swing.JTable salesTable;
    private javax.swing.JLabel titleL;
    private javax.swing.JLabel totalL;
    private javax.swing.JTextField totalTF;
    // End of variables declaration//GEN-END:variables
}
